-- Holdings ISWD zum 2026-09-29 (387 Aktienpositionen)
begin;

delete from public.etf_holdings
where etf_id = (select id from public.securities where ticker = 'ISWD')
  and as_of = '2026-09-29';

insert into public.etf_holdings (etf_id, holding_isin, holding_name, holding_ticker, holding_country, weight, as_of, source_url)
select s.id, v.key, v.name, v.ticker, v.country, v.weight, '2026-09-29', null
from public.securities s
cross join (values
  ('TICKER:MSFT:United States', 'MICROSOFT', 'MSFT', 'United States', 13.54),
  ('TICKER:MU:United States', 'MICRON TECHNOLOGY', 'MU', 'United States', 4.53),
  ('TICKER:TSLA:United States', 'TESLA INC', 'TSLA', 'United States', 3.8),
  ('TICKER:AMD:United States', 'ADVANCED MICRO DEVICES', 'AMD', 'United States', 3.74),
  ('TICKER:ASML:Netherlands', 'ASML HOLDING', 'ASML', 'Netherlands', 2.65),
  ('TICKER:XOM:United States', 'EXXONMOBIL HOLDINGS CORP', 'XOM', 'United States', 2.52),
  ('TICKER:JNJ:United States', 'JOHNSON & JOHNSON', 'JNJ', 'United States', 2.43),
  ('TICKER:INTC:United States', 'INTEL CORPORATION', 'INTC', 'United States', 1.92),
  ('TICKER:CSCO:United States', 'CISCO SYSTEMS INC', 'CSCO', 'United States', 1.59),
  ('TICKER:AMAT:United States', 'APPLIED MATERIAL INC', 'AMAT', 'United States', 1.53),
  ('TICKER:LRCX:United States', 'LAM RESEARCH', 'LRCX', 'United States', 1.53),
  ('TICKER:CVX:United States', 'CHEVRON', 'CVX', 'United States', 1.42),
  ('TICKER:PG:United States', 'PROCTER & GAMBLE', 'PG', 'United States', 1.3),
  ('TICKER:PANW:United States', 'PALO ALTO NETWORKS', 'PANW', 'United States', 1.19),
  ('TICKER:SHEL:United Kingdom', 'SHELL', 'SHEL', 'United Kingdom', 1.04),
  ('TICKER:GEV:United States', 'GE VERNOVA', 'GEV', 'United States', 0.97),
  ('TICKER:SNDK:United States', 'SANDISK', 'SNDK', 'United States', 0.97),
  ('TICKER:AZN:United Kingdom', 'ASTRAZENECA PLC', 'AZN', 'United Kingdom', 0.93),
  ('TICKER:LIN:United States', 'LINDE PLC', 'LIN', 'United States', 0.82),
  ('TICKER:BHP:Australia', 'BHP GROUP LTD', 'BHP', 'Australia', 0.82),
  ('TICKER:SAP:Germany', 'SAP', 'SAP', 'Germany', 0.8),
  ('TICKER:ADI:United States', 'ANALOG DEVICES', 'ADI', 'United States', 0.73),
  ('TICKER:QCOM:United States', 'QUALCOMM', 'QCOM', 'United States', 0.73),
  ('TICKER:SU:France', 'SCHNEIDER ELECTRIC', 'SU', 'France', 0.7),
  ('TICKER:TTE:France', 'TOTALENERGIES', 'TTE', 'France', 0.65),
  ('TICKER:WELL:United States', 'WELLTOWER', 'WELL', 'United States', 0.62),
  ('TICKER:DELL:United States', 'DELL TECHNOLOGIES INC CLASS C', 'DELL', 'United States', 0.61),
  ('TICKER:8035:Japan', 'TOKYO ELECTRON', '8035', 'Japan', 0.61),
  ('TICKER:WDC:United States', 'WESTERN DIGITAL CORP', 'WDC', 'United States', 0.58),
  ('TICKER:COP:United States', 'CONOCOPHILLIPS', 'COP', 'United States', 0.58),
  ('TICKER:6501:Japan', 'HITACHI', '6501', 'Japan', 0.58),
  ('TICKER:ABBN:Switzerland', 'ABB LTD', 'ABBN', 'Switzerland', 0.57),
  ('TICKER:ISRG:United States', 'INTUITIVE SURGICAL', 'ISRG', 'United States', 0.55),
  ('TICKER:DHR:United States', 'DANAHER', 'DHR', 'United States', 0.54),
  ('TICKER:NOW:United States', 'SERVICENOW', 'NOW', 'United States', 0.5),
  ('TICKER:ENR:Germany', 'SIEMENS ENERGY N AG', 'ENR', 'Germany', 0.48),
  ('TICKER:GLW:United States', 'CORNING', 'GLW', 'United States', 0.47),
  ('TICKER:NEM:United States', 'NEWMONT', 'NEM', 'United States', 0.47),
  ('TICKER:NOVO B:Denmark', 'NOVO NORDISK CLASS B', 'NOVO B', 'Denmark', 0.46),
  ('TICKER:UBER:United States', 'UBER TECHNOLOGIES', 'UBER', 'United States', 0.46),
  ('TICKER:AI:France', 'LAIR LIQUIDE SOCIETE ANONYME POUR', 'AI', 'France', 0.45),
  ('TICKER:VLO:United States', 'VALERO ENERGY CORP', 'VLO', 'United States', 0.43),
  ('TICKER:BP.:United Kingdom', 'BP PLC', 'BP.', 'United Kingdom', 0.43),
  ('TICKER:MDT:United States', 'MEDTRONIC PLC', 'MDT', 'United States', 0.42),
  ('TICKER:ACN:United States', 'ACCENTURE PLC CLASS A', 'ACN', 'United States', 0.41),
  ('TICKER:OR:France', 'LOREAL SA', 'OR', 'France', 0.39),
  ('TICKER:PSX:United States', 'PHILLIPS 66', 'PSX', 'United States', 0.39),
  ('TICKER:FCX:United States', 'FREEPORT MCMORAN INC', 'FCX', 'United States', 0.38),
  ('TICKER:TT:United States', 'TRANE TECHNOLOGIES PLC', 'TT', 'United States', 0.38),
  ('TICKER:MCK:United States', 'MCKESSON CORP', 'MCK', 'United States', 0.38),
  ('TICKER:RIO:United Kingdom', 'RIO TINTO', 'RIO', 'United Kingdom', 0.37),
  ('TICKER:CNQ:Canada', 'CANADIAN NATURAL RESOURCES LTD', 'CNQ', 'Canada', 0.37),
  ('TICKER:PWR:United States', 'QUANTA SERVICES INC', 'PWR', 'United States', 0.37),
  ('TICKER:AEM:Canada', 'AGNICO EAGLE MINES', 'AEM', 'Canada', 0.35),
  ('TICKER:ADBE:United States', 'ADOBE INC', 'ADBE', 'United States', 0.35),
  ('TICKER:JCI:United States', 'JOHNSON CONTROLS INTERNATIONAL PLC', 'JCI', 'United States', 0.35),
  ('TICKER:8058:Japan', 'MITSUBISHI', '8058', 'Japan', 0.34),
  ('TICKER:VRT:United States', 'VERTIV HOLDINGS CLASS A', 'VRT', 'United States', 0.34),
  ('TICKER:SAN:France', 'SANOFI SA', 'SAN', 'France', 0.34),
  ('TICKER:CDNS:United States', 'CADENCE DESIGN SYSTEMS', 'CDNS', 'United States', 0.33),
  ('TICKER:IFX:Germany', 'INFINEON TECHNOLOGIES AG', 'IFX', 'Germany', 0.33),
  ('TICKER:6981:Japan', 'MURATA MANUFACTURING', '6981', 'Japan', 0.31),
  ('TICKER:CEG:United States', 'CONSTELLATION ENERGY CORP', 'CEG', 'United States', 0.31),
  ('TICKER:HPE:United States', 'HEWLETT PACKARD ENTERPRISE', 'HPE', 'United States', 0.31),
  ('TICKER:SU:Canada', 'SUNCOR ENERGY INC', 'SU', 'Canada', 0.3),
  ('TICKER:REGN:United States', 'REGENERON PHARMACEUTICALS', 'REGN', 'United States', 0.29),
  ('TICKER:CP:Canada', 'CANADIAN PACIFIC KANSAS CITY', 'CP', 'Canada', 0.29),
  ('TICKER:EOG:United States', 'EOG RESOURCES', 'EOG', 'United States', 0.29),
  ('TICKER:MDLZ:United States', 'MONDELEZ INTERNATIONAL CLASS A', 'MDLZ', 'United States', 0.29),
  ('TICKER:SNPS:United States', 'SYNOPSYS', 'SNPS', 'United States', 0.28),
  ('TICKER:SLB:United States', 'SLB', 'SLB', 'United States', 0.28),
  ('TICKER:CMI:United States', 'CUMMINS INC', 'CMI', 'United States', 0.27),
  ('TICKER:8031:Japan', 'MITSUI', '8031', 'Japan', 0.27),
  ('TICKER:DASH:United States', 'DOORDASH CLASS A', 'DASH', 'United States', 0.26),
  ('TICKER:GLEN:United Kingdom', 'GLENCORE PLC', 'GLEN', 'United Kingdom', 0.26),
  ('TICKER:ABX:Canada', 'BARRICK MINING', 'ABX', 'Canada', 0.26),
  ('TICKER:CTAS:United States', 'CINTAS', 'CTAS', 'United States', 0.25),
  ('TICKER:ITX:Spain', 'INDUSTRIA DE DISENO TEXTIL SA', 'ITX', 'Spain', 0.25),
  ('TICKER:BSX:United States', 'BOSTON SCIENTIFIC CORP', 'BSX', 'United States', 0.24),
  ('TICKER:6752:Japan', 'PANASONIC HOLDINGS', '6752', 'Japan', 0.24),
  ('TICKER:TER:United States', 'TERADYNE', 'TER', 'United States', 0.24),
  ('TICKER:KEYS:United States', 'KEYSIGHT TECHNOLOGIES', 'KEYS', 'United States', 0.24),
  ('TICKER:TEL:United States', 'TE CONNECTIVITY PLC', 'TEL', 'United States', 0.23),
  ('TICKER:6503:Japan', 'MITSUBISHI ELECTRIC', '6503', 'Japan', 0.23),
  ('TICKER:WPM:Canada', 'WHEATON PRECIOUS METALS', 'WPM', 'Canada', 0.23),
  ('TICKER:4063:Japan', 'SHIN ETSU CHEMICAL', '4063', 'Japan', 0.23),
  ('TICKER:MNST:United States', 'MONSTER BEVERAGE', 'MNST', 'United States', 0.22),
  ('TICKER:AME:United States', 'AMETEK INC', 'AME', 'United States', 0.22),
  ('TICKER:FAST:United States', 'FASTENAL', 'FAST', 'United States', 0.22),
  ('TICKER:COR:United States', 'CENCORA', 'COR', 'United States', 0.22),
  ('TICKER:DG:France', 'VINCI SA', 'DG', 'France', 0.22),
  ('TICKER:AAL:United Kingdom', 'ANGLO AMERICAN PLC', 'AAL', 'United Kingdom', 0.21),
  ('TICKER:BKR:United States', 'BAKER HUGHES CLASS A', 'BKR', 'United States', 0.21),
  ('TICKER:GWW:United States', 'WW GRAINGER INC', 'GWW', 'United States', 0.2),
  ('TICKER:COHR:United States', 'COHERENT', 'COHR', 'United States', 0.2),
  ('TICKER:DVN:United States', 'DEVON ENERGY', 'DVN', 'United States', 0.2),
  ('TICKER:CTVA:United States', 'CORTEVA', 'CTVA', 'United States', 0.2),
  ('TICKER:NUE:United States', 'NUCOR', 'NUE', 'United States', 0.2),
  ('TICKER:ATCO A:Sweden', 'ATLAS COPCO CLASS A', 'ATCO A', 'Sweden', 0.2),
  ('TICKER:CAH:United States', 'CARDINAL HEALTH', 'CAH', 'United States', 0.2),
  ('TICKER:BAS:Germany', 'BASF N', 'BAS', 'Germany', 0.19),
  ('TICKER:A:United States', 'AGILENT TECHNOLOGIES INC', 'A', 'United States', 0.19),
  ('TICKER:WAB:United States', 'WESTINGHOUSE AIR BRAKE TECHNOLOGIE', 'WAB', 'United States', 0.19),
  ('TICKER:ENI:Italy', 'ENI', 'ENI', 'Italy', 0.19),
  ('TICKER:LONN:Switzerland', 'LONZA GROUP AG', 'LONN', 'Switzerland', 0.18),
  ('TICKER:FNV:Canada', 'FRANCO NEVADA', 'FNV', 'Canada', 0.18),
  ('TICKER:RACE:Italy', 'FERRARI', 'RACE', 'Italy', 0.18),
  ('TICKER:5803:Japan', 'FUJIKURA', '5803', 'Japan', 0.18),
  ('TICKER:EL:France', 'ESSILORLUXOTTICA SA', 'EL', 'France', 0.18),
  ('TICKER:ASM:Netherlands', 'ASM INTERNATIONAL NV', 'ASM', 'Netherlands', 0.18),
  ('TICKER:GRMN:United States', 'GARMIN', 'GRMN', 'United States', 0.18),
  ('TICKER:CLS:Canada', 'CELESTICA', 'CLS', 'Canada', 0.17),
  ('TICKER:WAT:United States', 'WATERS CORP', 'WAT', 'United States', 0.16),
  ('TICKER:RIO:Australia', 'RIO TINTO', 'RIO', 'Australia', 0.16),
  ('TICKER:RWE:Germany', 'RWE AG', 'RWE', 'Germany', 0.16),
  ('TICKER:IDXX:United States', 'IDEXX LABORATORIES', 'IDXX', 'United States', 0.16),
  ('TICKER:ADSK:United States', 'AUTODESK', 'ADSK', 'United States', 0.16),
  ('TICKER:WDS:Australia', 'WOODSIDE ENERGY GROUP LTD', 'WDS', 'Australia', 0.16),
  ('TICKER:6702:Japan', 'FUJITSU', '6702', 'Japan', 0.16),
  ('TICKER:8002:Japan', 'MARUBENI', '8002', 'Japan', 0.16),
  ('TICKER:FLEX:United States', 'FLEX LTD', 'FLEX', 'United States', 0.16),
  ('TICKER:TWLO:United States', 'TWILIO CLASS A', 'TWLO', 'United States', 0.16),
  ('TICKER:HOLN:Switzerland', 'HOLCIM LTD AG', 'HOLN', 'Switzerland', 0.16),
  ('TICKER:6301:Japan', 'KOMATSU', '6301', 'Japan', 0.15),
  ('TICKER:CVE:Canada', 'CENOVUS ENERGY', 'CVE', 'Canada', 0.15),
  ('TICKER:MSTR:United States', 'STRATEGY INC CLASS A', 'MSTR', 'United States', 0.15),
  ('TICKER:HLN:United Kingdom', 'HALEON PLC', 'HLN', 'United Kingdom', 0.15),
  ('TICKER:5802:Japan', 'SUMITOMO ELECTRIC INDUSTRIES', '5802', 'Japan', 0.15),
  ('TICKER:OXY:United States', 'OCCIDENTAL PETROLEUM CORP', 'OXY', 'United States', 0.15),
  ('TICKER:PRY:Italy', 'PRYSMIAN', 'PRY', 'Italy', 0.15),
  ('TICKER:SAND:Sweden', 'SANDVIK', 'SAND', 'Sweden', 0.15),
  ('TICKER:ADM:United States', 'ARCHER DANIELS MIDLAND', 'ADM', 'United States', 0.14),
  ('TICKER:CCO:Canada', 'CAMECO', 'CCO', 'Canada', 0.14),
  ('TICKER:6723:Japan', 'RENESAS ELECTRONICS CORP', '6723', 'Japan', 0.14),
  ('TICKER:WDAY:United States', 'WORKDAY CLASS A', 'WDAY', 'United States', 0.14),
  ('TICKER:FANG:United States', 'DIAMONDBACK ENERGY', 'FANG', 'United States', 0.14),
  ('TICKER:GALD:Switzerland', 'GALDERMA GROUP N AG', 'GALD', 'Switzerland', 0.14),
  ('TICKER:6701:Japan', 'NEC', '6701', 'Japan', 0.14),
  ('TICKER:REP:Spain', 'REPSOL', 'REP', 'Spain', 0.14),
  ('TICKER:DHI:United States', 'D R HORTON', 'DHI', 'United States', 0.14),
  ('TICKER:SDZ:Switzerland', 'SANDOZ GROUP AG', 'SDZ', 'Switzerland', 0.14),
  ('TICKER:SGO:France', 'COMPAGNIE DE SAINT GOBAIN SA', 'SGO', 'France', 0.13),
  ('TICKER:ROP:United States', 'ROPER TECHNOLOGIES', 'ROP', 'United States', 0.13),
  ('TICKER:NTR:Canada', 'NUTRIEN LTD', 'NTR', 'Canada', 0.13),
  ('TICKER:6762:Japan', 'TDK', '6762', 'Japan', 0.13),
  ('TICKER:JBL:United States', 'JABIL', 'JBL', 'United States', 0.13),
  ('TICKER:STMPA:France', 'STMICROELECTRONICS', 'STMPA', 'France', 0.13),
  ('TICKER:ODFL:United States', 'OLD DOMINION FREIGHT LINE', 'ODFL', 'United States', 0.13),
  ('TICKER:OKTA:United States', 'OKTA CLASS A', 'OKTA', 'United States', 0.13),
  ('TICKER:BIIB:United States', 'BIOGEN', 'BIIB', 'United States', 0.13),
  ('TICKER:RMD:United States', 'RESMED', 'RMD', 'United States', 0.12),
  ('TICKER:ALC:Switzerland', 'ALCON AG', 'ALC', 'Switzerland', 0.12),
  ('TICKER:VMC:United States', 'VULCAN MATERIALS', 'VMC', 'United States', 0.12),
  ('TICKER:AXON:United States', 'AXON ENTERPRISE', 'AXON', 'United States', 0.12),
  ('TICKER:6367:Japan', 'DAIKIN INDUSTRIES LTD', '6367', 'Japan', 0.12),
  ('TICKER:IR:United States', 'INGERSOLL RAND INC', 'IR', 'United States', 0.12),
  ('TICKER:TECK.B:Canada', 'TECK RESOURCES SUBORDINATE VOTING', 'TECK.B', 'Canada', 0.12),
  ('TICKER:4578:Japan', 'OTSUKA HOLDINGS', '4578', 'Japan', 0.11),
  ('TICKER:ON:United States', 'ON SEMICONDUCTOR CORP', 'ON', 'United States', 0.11),
  ('TICKER:4568:Japan', 'DAIICHI SANKYO LTD', '4568', 'Japan', 0.11),
  ('TICKER:STLD:United States', 'STEEL DYNAMICS INC', 'STLD', 'United States', 0.11),
  ('TICKER:TEAM:United States', 'ATLASSIAN CORP CLASS A', 'TEAM', 'United States', 0.11),
  ('TICKER:MLM:United States', 'MARTIN MARIETTA MATERIALS', 'MLM', 'United States', 0.11),
  ('TICKER:MT:France', 'ARCELORMITTAL SA', 'MT', 'France', 0.11),
  ('TICKER:K:Canada', 'KINROSS GOLD', 'K', 'Canada', 0.11),
  ('TICKER:EQT:United States', 'EQT', 'EQT', 'United States', 0.11),
  ('TICKER:WSM:United States', 'WILLIAMS SONOMA INC', 'WSM', 'United States', 0.11),
  ('TICKER:CTSH:United States', 'COGNIZANT TECHNOLOGY SOLUTIONS CLA', 'CTSH', 'United States', 0.11),
  ('TICKER:8015:Japan', 'TOYOTA TSUSHO', '8015', 'Japan', 0.11),
  ('TICKER:UCB:Belgium', 'UCB SA', 'UCB', 'Belgium', 0.11),
  ('TICKER:HPQ:United States', 'HP INC', 'HPQ', 'United States', 0.1),
  ('TICKER:VWS:Denmark', 'VESTAS WIND SYSTEMS', 'VWS', 'Denmark', 0.1),
  ('TICKER:FTI:United States', 'TECHNIPFMC PLC', 'FTI', 'United States', 0.1),
  ('TICKER:WST:United States', 'WEST PHARMACEUTICAL SERVICES', 'WST', 'United States', 0.1),
  ('TICKER:6971:Japan', 'KYOCERA', '6971', 'Japan', 0.1),
  ('TICKER:EQNR:Norway', 'EQUINOR', 'EQNR', 'Norway', 0.1),
  ('TICKER:Q:United States', 'QNITY ELECTRONICS', 'Q', 'United States', 0.1),
  ('TICKER:ADS:Germany', 'ADIDAS N AG', 'ADS', 'Germany', 0.1),
  ('TICKER:DOV:United States', 'DOVER CORP', 'DOV', 'United States', 0.1),
  ('TICKER:AMS:Spain', 'AMADEUS IT GROUP', 'AMS', 'Spain', 0.1),
  ('TICKER:NVT:United States', 'NVENT ELECTRIC PLC', 'NVT', 'United States', 0.1),
  ('TICKER:ATCO B:Sweden', 'ATLAS COPCO CLASS B', 'ATCO B', 'Sweden', 0.1),
  ('TICKER:FFIV:United States', 'F5', 'FFIV', 'United States', 0.1),
  ('TICKER:Z74:Singapore', 'SINGAPORE TELECOMMUNICATIONS LTD', 'Z74', 'Singapore', 0.09),
  ('TICKER:5108:Japan', 'BRIDGESTONE', '5108', 'Japan', 0.09),
  ('TICKER:4503:Japan', 'ASTELLAS PHARMA', '4503', 'Japan', 0.09),
  ('TICKER:ERIC B:Sweden', 'ERICSSON B', 'ERIC B', 'Sweden', 0.09),
  ('TICKER:HUBB:United States', 'HUBBELL INC', 'HUBB', 'United States', 0.09),
  ('TICKER:XYL:United States', 'XYLEM INC', 'XYL', 'United States', 0.09),
  ('TICKER:6273:Japan', 'SMC (JAPAN) CORP', '6273', 'Japan', 0.09),
  ('TICKER:1:Hong Kong', 'CK HUTCHISON HOLDINGS', '1', 'Hong Kong', 0.09),
  ('TICKER:4901:Japan', 'FUJIFILM HOLDINGS', '4901', 'Japan', 0.09),
  ('TICKER:PHM:United States', 'PULTEGROUP', 'PHM', 'United States', 0.09),
  ('TICKER:669:Hong Kong', 'TECHTRONIC INDUSTRIES', '669', 'Hong Kong', 0.09),
  ('TICKER:CHD:United States', 'CHURCH AND DWIGHT INC', 'CHD', 'United States', 0.09),
  ('TICKER:7751:Japan', 'CANON', '7751', 'Japan', 0.09),
  ('TICKER:ML:France', 'MICHELIN', 'ML', 'France', 0.09),
  ('TICKER:FM:Canada', 'FIRST QUANTUM MINERALS', 'FM', 'Canada', 0.08),
  ('TICKER:5020:Japan', 'ENEOS HOLDINGS', '5020', 'Japan', 0.08),
  ('TICKER:NST:Australia', 'NORTHERN STAR RESOURCES LTD', 'NST', 'Australia', 0.08),
  ('TICKER:HEI:Germany', 'HEIDELBERG MATERIALS AG', 'HEI', 'Germany', 0.08),
  ('TICKER:VACN:Switzerland', 'VAT GROUP AG', 'VACN', 'Switzerland', 0.08),
  ('TICKER:HEXA B:Sweden', 'HEXAGON CLASS B', 'HEXA B', 'Sweden', 0.08),
  ('TICKER:FRE:Germany', 'FRESENIUS N', 'FRE', 'Germany', 0.08),
  ('TICKER:6920:Japan', 'LASERTEC', '6920', 'Japan', 0.08),
  ('TICKER:STE:United States', 'STERIS', 'STE', 'United States', 0.08),
  ('TICKER:RS:United States', 'RELIANCE STEEL & ALUMINUM', 'RS', 'United States', 0.08),
  ('TICKER:1605:Japan', 'INPEX', '1605', 'Japan', 0.08),
  ('TICKER:MRK:Germany', 'MERCK', 'MRK', 'Germany', 0.08),
  ('TICKER:IFF:United States', 'INTERNATIONAL FLAVORS & FRAGRANCES', 'IFF', 'United States', 0.08),
  ('TICKER:4452:Japan', 'KAO', '4452', 'Japan', 0.07),
  ('TICKER:EXE:United States', 'EXPAND ENERGY', 'EXE', 'United States', 0.07),
  ('TICKER:PHIA:Netherlands', 'KONINKLIJKE PHILIPS', 'PHIA', 'Netherlands', 0.07),
  ('TICKER:TPL:United States', 'TEXAS PACIFIC LAND', 'TPL', 'United States', 0.07),
  ('TICKER:PAAS:Canada', 'PAN AMERICAN SILVER', 'PAAS', 'Canada', 0.07),
  ('TICKER:7269:Japan', 'SUZUKI MOTOR', '7269', 'Japan', 0.07),
  ('TICKER:DOW:United States', 'DOW', 'DOW', 'United States', 0.07),
  ('TICKER:EVN:Australia', 'EVOLUTION MINING', 'EVN', 'Australia', 0.07),
  ('TICKER:AMRZ:United States', 'AMRIZE AG', 'AMRZ', 'United States', 0.07),
  ('TICKER:CRS:United States', 'CARPENTER TECHNOLOGY', 'CRS', 'United States', 0.07),
  ('TICKER:4543:Japan', 'TERUMO', '4543', 'Japan', 0.07),
  ('TICKER:STO:Australia', 'SANTOS', 'STO', 'Australia', 0.07),
  ('TICKER:DSFIR:Netherlands', 'DSM FIRMENICH AG', 'DSFIR', 'Netherlands', 0.07),
  ('TICKER:CDE:United States', 'COEUR MINING', 'CDE', 'United States', 0.07),
  ('TICKER:6902:Japan', 'DENSO', '6902', 'Japan', 0.07),
  ('TICKER:FSLR:United States', 'FIRST SOLAR', 'FSLR', 'United States', 0.07),
  ('TICKER:KNEBV:Finland', 'KONE', 'KNEBV', 'Finland', 0.07),
  ('TICKER:7936:Japan', 'ASICS', '7936', 'Japan', 0.07),
  ('TICKER:KRX:Ireland', 'KINGSPAN GROUP PLC', 'KRX', 'Ireland', 0.07),
  ('TICKER:BBY:United States', 'BEST BUY', 'BBY', 'United States', 0.07),
  ('TICKER:FMG:Australia', 'FORTESCUE LTD', 'FMG', 'Australia', 0.07),
  ('TICKER:HLMA:United Kingdom', 'HALMA PLC', 'HLMA', 'United Kingdom', 0.07),
  ('TICKER:IMO:Canada', 'IMPERIAL OIL LTD', 'IMO', 'Canada', 0.07),
  ('TICKER:GPC:United States', 'GENUINE PARTS', 'GPC', 'United States', 0.07),
  ('TICKER:HEI A:United States', 'HEICO CLASS A', 'HEI A', 'United States', 0.07),
  ('TICKER:IEX:United States', 'IDEX', 'IEX', 'United States', 0.07),
  ('TICKER:DD:United States', 'DUPONT DE NEMOURS', 'DD', 'United States', 0.07),
  ('TICKER:CAP:France', 'CAPGEMINI', 'CAP', 'France', 0.07),
  ('TICKER:MG:Canada', 'MAGNA INTERNATIONAL', 'MG', 'Canada', 0.06),
  ('TICKER:2:Hong Kong', 'CLP HOLDINGS', '2', 'Hong Kong', 0.06),
  ('TICKER:WSP:Canada', 'WSP GLOBAL INC', 'WSP', 'Canada', 0.06),
  ('TICKER:LEN:United States', 'LENNAR A CLASS A', 'LEN', 'United States', 0.06),
  ('TICKER:CF:United States', 'CF INDUSTRIES HOLDINGS INC', 'CF', 'United States', 0.06),
  ('TICKER:JBHT:United States', 'JB HUNT TRANSPORT SERVICES', 'JBHT', 'United States', 0.06),
  ('TICKER:ANTO:United Kingdom', 'ANTOFAGASTA PLC', 'ANTO', 'United Kingdom', 0.06),
  ('TICKER:LUN:Canada', 'LUNDIN MINING', 'LUN', 'Canada', 0.06),
  ('TICKER:IP:United States', 'INTERNATIONAL PAPER', 'IP', 'United States', 0.06),
  ('TICKER:9101:Japan', 'NIPPON YUSEN', '9101', 'Japan', 0.06),
  ('TICKER:WRT1V:Finland', 'WARTSILA', 'WRT1V', 'Finland', 0.06),
  ('TICKER:PTC:United States', 'PTC', 'PTC', 'United States', 0.06),
  ('TICKER:ALFA:Sweden', 'ALFA LAVAL', 'ALFA', 'Sweden', 0.06),
  ('TICKER:WCP:Canada', 'WHITECAP RESOURCES INC', 'WCP', 'Canada', 0.06),
  ('TICKER:DSY:France', 'DASSAULT SYSTEMES', 'DSY', 'France', 0.06),
  ('TICKER:FTV:United States', 'FORTIVE', 'FTV', 'United States', 0.06),
  ('TICKER:ESSITY B:Sweden', 'ESSITY CLASS B', 'ESSITY B', 'Sweden', 0.06),
  ('TICKER:NESTE:Finland', 'NESTE', 'NESTE', 'Finland', 0.06),
  ('TICKER:EPI A:Sweden', 'EPIROC CLASS A', 'EPI A', 'Sweden', 0.06),
  ('TICKER:S32:Australia', 'SOUTH32', 'S32', 'Australia', 0.06),
  ('TICKER:SN:United States', 'SHARKNINJA', 'SN', 'United States', 0.06),
  ('TICKER:5713:Japan', 'SUMITOMO METAL MINING', '5713', 'Japan', 0.06),
  ('TICKER:INF:United Kingdom', 'INFORMA PLC', 'INF', 'United Kingdom', 0.06),
  ('TICKER:FN:United States', 'FABRINET', 'FN', 'United States', 0.06),
  ('TICKER:ELE:Spain', 'ENDESA SA', 'ELE', 'Spain', 0.06),
  ('TICKER:UPM:Finland', 'UPM-KYMMENE', 'UPM', 'Finland', 0.06),
  ('TICKER:SGRO:United Kingdom', 'SEGRO REIT PLC', 'SGRO', 'United Kingdom', 0.06),
  ('TICKER:FPH:New Zealand', 'FISHER AND PAYKEL HEALTHCARE CORPO', 'FPH', 'New Zealand', 0.06),
  ('TICKER:TOU:Canada', 'TOURMALINE OIL CORP', 'TOU', 'Canada', 0.06),
  ('TICKER:WY:United States', 'WEYERHAEUSER REIT', 'WY', 'United States', 0.05),
  ('TICKER:BOL:Sweden', 'BOLIDEN', 'BOL', 'Sweden', 0.05),
  ('TICKER:6988:Japan', 'NITTO DENKO', '6988', 'Japan', 0.05),
  ('TICKER:AGI:Canada', 'ALAMOS GOLD CLASS A', 'AGI', 'Canada', 0.05),
  ('TICKER:DPLM:United Kingdom', 'DIPLOMA PLC', 'DPLM', 'United Kingdom', 0.05),
  ('TICKER:DAL:United States', 'DELTA AIR LINES', 'DAL', 'United States', 0.05),
  ('TICKER:CRCL:United States', 'CIRCLE INTERNET GROUP INC CLASS A', 'CRCL', 'United States', 0.05),
  ('TICKER:HEI:United States', 'HEICO', 'HEI', 'United States', 0.05),
  ('TICKER:7735:Japan', 'SCREEN HOLDINGS LTD', '7735', 'Japan', 0.05),
  ('TICKER:6525:Japan', 'KOKUSAI ELECTRIC', '6525', 'Japan', 0.05),
  ('TICKER:9532:Japan', 'OSAKA GAS', '9532', 'Japan', 0.05),
  ('TICKER:MTZ:United States', 'MASTEC INC', 'MTZ', 'United States', 0.05),
  ('TICKER:6361:Japan', 'EBARA', '6361', 'Japan', 0.05),
  ('TICKER:5016:Japan', 'JX ADVANCED METALS CORP', '5016', 'Japan', 0.05),
  ('TICKER:OMV:Austria', 'OMV', 'OMV', 'Austria', 0.05),
  ('TICKER:TRI:Canada', 'THOMSON REUTERS CORP', 'TRI', 'Canada', 0.05),
  ('TICKER:1812:Japan', 'KAJIMA', '1812', 'Japan', 0.05),
  ('TICKER:823:Hong Kong', 'LINK REAL ESTATE INVESTMENT TRUST', '823', 'Hong Kong', 0.05),
  ('TICKER:ORG:Australia', 'ORIGIN ENERGY', 'ORG', 'Australia', 0.05),
  ('TICKER:AKRBP:Norway', 'AKER BP', 'AKRBP', 'Norway', 0.05),
  ('TICKER:NBIX:United States', 'NEUROCRINE BIOSCIENCES', 'NBIX', 'United States', 0.05),
  ('TICKER:MAERSK B:Denmark', 'A P MOLLER MAERSK B', 'MAERSK B', 'Denmark', 0.05),
  ('TICKER:7733:Japan', 'OLYMPUS', '7733', 'Japan', 0.05),
  ('TICKER:EQX:Canada', 'EQUINOX GOLD', 'EQX', 'Canada', 0.05),
  ('TICKER:METSO:Finland', 'METSO CORPORATION', 'METSO', 'Finland', 0.05),
  ('TICKER:MKC:United States', 'MCCORMICK & CO NON-VOTING', 'MKC', 'United States', 0.05),
  ('TICKER:TIH:Canada', 'TOROMONT INDUSTRIES LTD', 'TIH', 'Canada', 0.05),
  ('TICKER:STMN:Switzerland', 'STRAUMANN HOLDING AG', 'STMN', 'Switzerland', 0.05),
  ('TICKER:6504:Japan', 'FUJI ELECTRIC', '6504', 'Japan', 0.05),
  ('TICKER:FORTUM:Finland', 'FORTUM', 'FORTUM', 'Finland', 0.05),
  ('TICKER:4307:Japan', 'NOMURA RESEARCH INSTITUTE', '4307', 'Japan', 0.05),
  ('TICKER:MONC:Italy', 'MONCLER', 'MONC', 'Italy', 0.04),
  ('TICKER:3407:Japan', 'ASAHI KASEI', '3407', 'Japan', 0.04),
  ('TICKER:GIB.A:Canada', 'CGI INC CLASS A', 'GIB.A', 'Canada', 0.04),
  ('TICKER:HEN3:Germany', 'HENKEL & KGAA PREF AG', 'HEN3', 'Germany', 0.04),
  ('TICKER:NHY:Norway', 'NORSK HYDRO', 'NHY', 'Norway', 0.04),
  ('TICKER:COO:United States', 'COOPER', 'COO', 'United States', 0.04),
  ('TICKER:6594:Japan', 'NIDEC', '6594', 'Japan', 0.04),
  ('TICKER:EDV:United Kingdom', 'ENDEAVOUR MINING', 'EDV', 'United Kingdom', 0.04),
  ('TICKER:G1A:Germany', 'GEA GROUP AG', 'G1A', 'Germany', 0.04),
  ('TICKER:RYA:Ireland', 'RYANAIR HOLDINGS PLC', 'RYA', 'Ireland', 0.04),
  ('TICKER:1801:Japan', 'TAISEI', '1801', 'Japan', 0.04),
  ('TICKER:EN:France', 'BOUYGUES SA', 'EN', 'France', 0.04),
  ('TICKER:WSO:United States', 'WATSCO', 'WSO', 'United States', 0.04),
  ('TICKER:3402:Japan', 'TORAY INDUSTRIES', '3402', 'Japan', 0.04),
  ('TICKER:ATRL:Canada', 'ATKINSREALIS GROUP INC', 'ATRL', 'Canada', 0.04),
  ('TICKER:SMIN:United Kingdom', 'SMITHS GROUP PLC', 'SMIN', 'United Kingdom', 0.04),
  ('TICKER:ORNBV:Finland', 'ORION CLASS B', 'ORNBV', 'Finland', 0.04),
  ('TICKER:SKF B:Sweden', 'SKF B', 'SKF B', 'Sweden', 0.04),
  ('TICKER:GALP:Portugal', 'GALP ENERGIA SGPS SA CLASS B', 'GALP', 'Portugal', 0.04),
  ('TICKER:QIA:Germany', 'QIAGEN', 'QIA', 'Germany', 0.04),
  ('TICKER:CCL.B:Canada', 'CCL INDUSTRIES CLASS B', 'CCL.B', 'Canada', 0.04),
  ('TICKER:BEAN:Switzerland', 'BELIMO N AG', 'BEAN', 'Switzerland', 0.04),
  ('TICKER:MOWI:Norway', 'MOWI', 'MOWI', 'Norway', 0.04),
  ('TICKER:SKA B:Sweden', 'SKANSKA B', 'SKA B', 'Sweden', 0.04),
  ('TICKER:SIG:Australia', 'SIGMA HEALTHCARE', 'SIG', 'Australia', 0.04),
  ('TICKER:TEN:Italy', 'TENARIS SA', 'TEN', 'Italy', 0.04),
  ('TICKER:LISN:Switzerland', 'CHOCOLADEFABRIKEN LINDT & SPRUENGL', 'LISN', 'Switzerland', 0.03),
  ('TICKER:STLAM:Italy', 'STELLANTIS', 'STLAM', 'Italy', 0.03),
  ('TICKER:ROL:United States', 'ROLLINS INC', 'ROL', 'United States', 0.03),
  ('TICKER:4911:Japan', 'SHISEIDO', '4911', 'Japan', 0.03),
  ('TICKER:TREL B:Sweden', 'TRELLEBORG B', 'TREL B', 'Sweden', 0.03),
  ('TICKER:EPI B:Sweden', 'EPIROC CLASS B', 'EPI B', 'Sweden', 0.03),
  ('TICKER:LYC:Australia', 'LYNAS RARE EARTHS', 'LYC', 'Australia', 0.03),
  ('TICKER:BEI:Germany', 'BEIERSDORF AG', 'BEI', 'Germany', 0.03),
  ('TICKER:1308:Hong Kong', 'SITC INTERNATIONAL HOLDINGS LTD', '1308', 'Hong Kong', 0.03),
  ('TICKER:BNR:Germany', 'BRENNTAG', 'BNR', 'Germany', 0.03),
  ('TICKER:LISP:Switzerland', 'CHOCOLADEFABRIKEN LINDT & SPRUENGL', 'LISP', 'Switzerland', 0.03),
  ('TICKER:C6L:Singapore', 'SINGAPORE AIRLINES LTD', 'C6L', 'Singapore', 0.03),
  ('TICKER:5706:Japan', 'MITSUI KINZOKU LIMITED LTD', '5706', 'Japan', 0.03),
  ('TICKER:9107:Japan', 'KAWASAKI KISEN LTD', '9107', 'Japan', 0.03),
  ('TICKER:MAERSK A:Denmark', 'A P MOLLER MAERSK', 'MAERSK A', 'Denmark', 0.03),
  ('TICKER:STN:Canada', 'STANTEC', 'STN', 'Canada', 0.03),
  ('TICKER:SOBI:Sweden', 'SWEDISH ORPHAN BIOVITRUM', 'SOBI', 'Sweden', 0.03),
  ('TICKER:PSON:United Kingdom', 'PEARSON PLC', 'PSON', 'United Kingdom', 0.03),
  ('TICKER:SYENS:Belgium', 'SYENSQO NV', 'SYENS', 'Belgium', 0.03),
  ('TICKER:7912:Japan', 'DAI NIPPON PRINTING', '7912', 'Japan', 0.03),
  ('TICKER:5019:Japan', 'IDEMITSU KOSAN LTD', '5019', 'Japan', 0.03),
  ('TICKER:LIFCO B:Sweden', 'LIFCO CLASS B', 'LIFCO B', 'Sweden', 0.03),
  ('TICKER:UHR:Switzerland', 'THE SWATCH GROUP AG', 'UHR', 'Switzerland', 0.03),
  ('TICKER:6586:Japan', 'MAKITA', '6586', 'Japan', 0.03),
  ('TICKER:9843:Japan', 'NITORI HOLDINGS', '9843', 'Japan', 0.03),
  ('TICKER:7202:Japan', 'ISUZU MOTORS', '7202', 'Japan', 0.03),
  ('TICKER:4523:Japan', 'EISAI', '4523', 'Japan', 0.03),
  ('TICKER:EMSN:Switzerland', 'EMS-CHEMIE HOLDING AG', 'EMSN', 'Switzerland', 0.03),
  ('TICKER:7259:Japan', 'AISIN', '7259', 'Japan', 0.03),
  ('TICKER:INDT:Sweden', 'INDUTRADE', 'INDT', 'Sweden', 0.03),
  ('TICKER:6479:Japan', 'MINEBEA MITSUMI INC', '6479', 'Japan', 0.03),
  ('TICKER:1803:Japan', 'SHIMIZU', '1803', 'Japan', 0.03),
  ('TICKER:8113:Japan', 'UNICHARM', '8113', 'Japan', 0.03),
  ('TICKER:KGF:United Kingdom', 'KINGFISHER PLC', 'KGF', 'United Kingdom', 0.03),
  ('TICKER:SCA B:Sweden', 'SVENSKA CELLULOSA B', 'SCA B', 'Sweden', 0.03),
  ('TICKER:YAR:Norway', 'YARA INTERNATIONAL', 'YAR', 'Norway', 0.03),
  ('TICKER:7911:Japan', 'TOPPAN HOLDINGS', '7911', 'Japan', 0.02),
  ('TICKER:ABF:United Kingdom', 'ASSOCIATED BRITISH FOODS PLC', 'ABF', 'United Kingdom', 0.02),
  ('TICKER:66:Hong Kong', 'MTR CORPORATION', '66', 'Hong Kong', 0.02),
  ('TICKER:BEIJ B:Sweden', 'BEIJER REF CLASS B', 'BEIJ B', 'Sweden', 0.02),
  ('TICKER:1878:Japan', 'DAITO TRUST CONSTRUCTION LTD', '1878', 'Japan', 0.02),
  ('TICKER:5201:Japan', 'AGC', '5201', 'Japan', 0.02),
  ('TICKER:SAP:Canada', 'SAPUTO', 'SAP', 'Canada', 0.02),
  ('TICKER:EVK:Germany', 'EVONIK INDUSTRIES AG', 'EVK', 'Germany', 0.02),
  ('TICKER:ALO:France', 'ALSTOM SA', 'ALO', 'France', 0.02),
  ('TICKER:HEN:Germany', 'HENKEL AG', 'HEN', 'Germany', 0.02),
  ('TICKER:VER:Austria', 'VERBUND AG', 'VER', 'Austria', 0.02),
  ('TICKER:IPN:France', 'IPSEN SA', 'IPN', 'France', 0.02),
  ('TICKER:12:Hong Kong', 'HENDERSON LAND DEVELOPMENT LTD', '12', 'Hong Kong', 0.02),
  ('TICKER:VAR:Norway', 'VAR ENERGI', 'VAR', 'Norway', 0.02),
  ('TICKER:2587:Japan', 'SUNTORY BEVERAGE & FOOD LTD', '2587', 'Japan', 0.02),
  ('TICKER:LOTB:Belgium', 'LOTUS BAKERIES NV', 'LOTB', 'Belgium', 0.02),
  ('TICKER:P911:Germany', 'DR ING HC F PORSCHE PRF AG', 'P911', 'Germany', 0.02),
  ('TICKER:19:Hong Kong', 'SWIRE PACIFIC LTD A', '19', 'Hong Kong', 0.02),
  ('TICKER:NEM:Germany', 'NEMETSCHEK', 'NEM', 'Germany', 0.02),
  ('TICKER:BIM:France', 'BIOMERIEUX SA', 'BIM', 'France', 0.01),
  ('TICKER:MEL:New Zealand', 'MERIDIAN ENERGY LTD', 'MEL', 'New Zealand', 0.01),
  ('TICKER:BKW:Switzerland', 'BKW N AG', 'BKW', 'Switzerland', 0.01),
  ('TICKER:BZU:Italy', 'BUZZI', 'BZU', 'Italy', 0.01),
  ('TICKER:4151:Japan', 'KYOWA KIRIN LTD', '4151', 'Japan', 0.01),
  ('TICKER:1038:Hong Kong', 'CHEUNG KONG INFRASTRUCTURE HOLDING', '1038', 'Hong Kong', 0.01),
  ('TICKER:HOLX:United States', 'HOLOGIC INC', 'HOLX', 'United States', 0),
  ('TICKER:2299955D:Canada', 'CONSTELLATION SOFTWARE INC', '2299955D', 'Canada', 0)
) as v(key, name, ticker, country, weight)
where s.ticker = 'ISWD';

commit;
