-- supabase_seed_securities.sql
--
-- Einmalig: legt die Titel aus src/data/stocks.js in der Tabelle securities an
-- (503 Aktien, 1 ETF). Im Supabase SQL Editor NACH
-- supabase_schema_screening.sql ausführen. Wiederholbar: vorhandene Titel
-- werden nicht überschrieben (on conflict do nothing), damit manuelle
-- Änderungen erhalten bleiben.
--
-- Aktiengattung: share_class = 'common'. Grundlage: Die Titel stammen aus dem
-- S&P 500, der laut Indexmethodik nur Stammaktien aufnimmt (D1/D2). Bei Titeln
-- außerhalb des S&P 500 die Gattung einzeln prüfen.
-- ISIN und deutsche Handelsplätze füllt der Cron (FMP-Profil, OpenFIGI).
-- ETF: ISIN/UCITS/Basisinformationsblatt aus den verifizierten Stammdaten in
-- stocks.js. Datum des letzten Fonds-Jahresberichts (fund_annual_report_date)
-- bitte selbst eintragen — ohne dieses Datum laufen G2–G5 nie als gültig.

insert into public.securities
  (ticker, name, asset_type, product_type, share_class, data_provider, provider_symbol)
values
  ('A', 'Agilent Technologies, Inc.', 'stock', 'standard', 'common', 'fmp', 'A'),
  ('AAPL', 'Apple Inc.', 'stock', 'standard', 'common', 'fmp', 'AAPL'),
  ('ABBV', 'AbbVie Inc.', 'stock', 'standard', 'common', 'fmp', 'ABBV'),
  ('ABNB', 'Airbnb, Inc.', 'stock', 'standard', 'common', 'fmp', 'ABNB'),
  ('ABT', 'Abbott Laboratories', 'stock', 'standard', 'common', 'fmp', 'ABT'),
  ('ACGL', 'Arch Capital Group Ltd.', 'stock', 'standard', 'common', 'fmp', 'ACGL'),
  ('ACN', 'Accenture plc', 'stock', 'standard', 'common', 'fmp', 'ACN'),
  ('ADBE', 'Adobe Inc.', 'stock', 'standard', 'common', 'fmp', 'ADBE'),
  ('ADI', 'Analog Devices, Inc.', 'stock', 'standard', 'common', 'fmp', 'ADI'),
  ('ADM', 'Archer-Daniels-Midland Company', 'stock', 'standard', 'common', 'fmp', 'ADM'),
  ('ADP', 'Automatic Data Processing, Inc.', 'stock', 'standard', 'common', 'fmp', 'ADP'),
  ('ADSK', 'Autodesk, Inc.', 'stock', 'standard', 'common', 'fmp', 'ADSK'),
  ('AEE', 'Ameren Corporation', 'stock', 'standard', 'common', 'fmp', 'AEE'),
  ('AEP', 'American Electric Power Company', 'stock', 'standard', 'common', 'fmp', 'AEP'),
  ('AES', 'The AES Corporation', 'stock', 'standard', 'common', 'fmp', 'AES'),
  ('AFL', 'AFLAC Incorporated', 'stock', 'standard', 'common', 'fmp', 'AFL'),
  ('AIG', 'American International Group, I', 'stock', 'standard', 'common', 'fmp', 'AIG'),
  ('AIZ', 'Assurant, Inc.', 'stock', 'standard', 'common', 'fmp', 'AIZ'),
  ('AJG', 'Arthur J. Gallagher & Co.', 'stock', 'standard', 'common', 'fmp', 'AJG'),
  ('AKAM', 'Akamai Technologies, Inc.', 'stock', 'standard', 'common', 'fmp', 'AKAM'),
  ('ALB', 'Albemarle Corporation', 'stock', 'standard', 'common', 'fmp', 'ALB'),
  ('ALGN', 'Align Technology, Inc.', 'stock', 'standard', 'common', 'fmp', 'ALGN'),
  ('ALL', 'Allstate Corporation (The)', 'stock', 'standard', 'common', 'fmp', 'ALL'),
  ('ALLE', 'Allegion plc', 'stock', 'standard', 'common', 'fmp', 'ALLE'),
  ('AMAT', 'Applied Materials, Inc.', 'stock', 'standard', 'common', 'fmp', 'AMAT'),
  ('AMCR', 'Amcor plc', 'stock', 'standard', 'common', 'fmp', 'AMCR'),
  ('AMD', 'Advanced Micro Devices, Inc.', 'stock', 'standard', 'common', 'fmp', 'AMD'),
  ('AME', 'AMETEK, Inc.', 'stock', 'standard', 'common', 'fmp', 'AME'),
  ('AMGN', 'Amgen Inc.', 'stock', 'standard', 'common', 'fmp', 'AMGN'),
  ('AMP', 'Ameriprise Financial, Inc.', 'stock', 'standard', 'common', 'fmp', 'AMP'),
  ('AMT', 'American Tower Corporation (REI', 'stock', 'standard', 'common', 'fmp', 'AMT'),
  ('AMZN', 'Amazon.com, Inc.', 'stock', 'standard', 'common', 'fmp', 'AMZN'),
  ('ANET', 'Arista Networks, Inc.', 'stock', 'standard', 'common', 'fmp', 'ANET'),
  ('AON', 'Aon plc', 'stock', 'standard', 'common', 'fmp', 'AON'),
  ('AOS', 'A.O. Smith Corporation', 'stock', 'standard', 'common', 'fmp', 'AOS'),
  ('APA', 'APA Corporation', 'stock', 'standard', 'common', 'fmp', 'APA'),
  ('APD', 'Air Products and Chemicals, Inc', 'stock', 'standard', 'common', 'fmp', 'APD'),
  ('APH', 'Amphenol Corporation', 'stock', 'standard', 'common', 'fmp', 'APH'),
  ('APO', 'Apollo Global Management, Inc.', 'stock', 'standard', 'common', 'fmp', 'APO'),
  ('APP', 'Applovin Corporation', 'stock', 'standard', 'common', 'fmp', 'APP'),
  ('APTV', 'Aptiv PLC', 'stock', 'standard', 'common', 'fmp', 'APTV'),
  ('ARE', 'Alexandria Real Estate Equities', 'stock', 'standard', 'common', 'fmp', 'ARE'),
  ('ARES', 'Ares Management Corporation', 'stock', 'standard', 'common', 'fmp', 'ARES'),
  ('ATO', 'Atmos Energy Corporation', 'stock', 'standard', 'common', 'fmp', 'ATO'),
  ('AVB', 'AvalonBay Communities, Inc.', 'stock', 'standard', 'common', 'fmp', 'AVB'),
  ('AVGO', 'Broadcom Inc.', 'stock', 'standard', 'common', 'fmp', 'AVGO'),
  ('AVY', 'Avery Dennison Corporation', 'stock', 'standard', 'common', 'fmp', 'AVY'),
  ('AWK', 'American Water Works Company, I', 'stock', 'standard', 'common', 'fmp', 'AWK'),
  ('AXON', 'Axon Enterprise, Inc.', 'stock', 'standard', 'common', 'fmp', 'AXON'),
  ('AXP', 'American Express Company', 'stock', 'standard', 'common', 'fmp', 'AXP'),
  ('AZO', 'AutoZone, Inc.', 'stock', 'standard', 'common', 'fmp', 'AZO'),
  ('BA', 'Boeing Company (The)', 'stock', 'standard', 'common', 'fmp', 'BA'),
  ('BAC', 'Bank of America Corporation', 'stock', 'standard', 'common', 'fmp', 'BAC'),
  ('BALL', 'Ball Corporation', 'stock', 'standard', 'common', 'fmp', 'BALL'),
  ('BAX', 'Baxter International Inc.', 'stock', 'standard', 'common', 'fmp', 'BAX'),
  ('BBY', 'Best Buy Co., Inc.', 'stock', 'standard', 'common', 'fmp', 'BBY'),
  ('BDX', 'Becton, Dickinson and Company', 'stock', 'standard', 'common', 'fmp', 'BDX'),
  ('BEN', 'Franklin Resources, Inc.', 'stock', 'standard', 'common', 'fmp', 'BEN'),
  ('BF-B', 'Brown Forman Inc', 'stock', 'standard', 'common', 'fmp', 'BF-B'),
  ('BG', 'Bunge Limited', 'stock', 'standard', 'common', 'fmp', 'BG'),
  ('BIIB', 'Biogen Inc.', 'stock', 'standard', 'common', 'fmp', 'BIIB'),
  ('BKNG', 'Booking Holdings Inc. Common St', 'stock', 'standard', 'common', 'fmp', 'BKNG'),
  ('BKR', 'Baker Hughes Company', 'stock', 'standard', 'common', 'fmp', 'BKR'),
  ('BLDR', 'Builders FirstSource, Inc.', 'stock', 'standard', 'common', 'fmp', 'BLDR'),
  ('BLK', 'BlackRock, Inc.', 'stock', 'standard', 'common', 'fmp', 'BLK'),
  ('BMY', 'Bristol-Myers Squibb Company', 'stock', 'standard', 'common', 'fmp', 'BMY'),
  ('BNY', 'The Bank of New York Mellon Cor', 'stock', 'standard', 'common', 'fmp', 'BNY'),
  ('BR', 'Broadridge Financial Solutions,', 'stock', 'standard', 'common', 'fmp', 'BR'),
  ('BRK-B', 'Berkshire Hathaway Inc. New', 'stock', 'standard', 'common', 'fmp', 'BRK-B'),
  ('BRO', 'Brown & Brown, Inc.', 'stock', 'standard', 'common', 'fmp', 'BRO'),
  ('BSX', 'Boston Scientific Corporation', 'stock', 'standard', 'common', 'fmp', 'BSX'),
  ('BX', 'Blackstone Inc.', 'stock', 'standard', 'common', 'fmp', 'BX'),
  ('BXP', 'BXP, Inc.', 'stock', 'standard', 'common', 'fmp', 'BXP'),
  ('C', 'Citigroup, Inc.', 'stock', 'standard', 'common', 'fmp', 'C'),
  ('CAH', 'Cardinal Health, Inc.', 'stock', 'standard', 'common', 'fmp', 'CAH'),
  ('CARR', 'Carrier Global Corporation', 'stock', 'standard', 'common', 'fmp', 'CARR'),
  ('CASY', 'Caseys General Stores, Inc.', 'stock', 'standard', 'common', 'fmp', 'CASY'),
  ('CAT', 'Caterpillar, Inc.', 'stock', 'standard', 'common', 'fmp', 'CAT'),
  ('CB', 'Chubb Limited', 'stock', 'standard', 'common', 'fmp', 'CB'),
  ('CBOE', 'Cboe Global Markets, Inc.', 'stock', 'standard', 'common', 'fmp', 'CBOE'),
  ('CBRE', 'CBRE Group Inc', 'stock', 'standard', 'common', 'fmp', 'CBRE'),
  ('CCI', 'Crown Castle Inc.', 'stock', 'standard', 'common', 'fmp', 'CCI'),
  ('CCL', 'Carnival Corporation Ltd.', 'stock', 'standard', 'common', 'fmp', 'CCL'),
  ('CDNS', 'Cadence Design Systems, Inc.', 'stock', 'standard', 'common', 'fmp', 'CDNS'),
  ('CDW', 'CDW Corporation', 'stock', 'standard', 'common', 'fmp', 'CDW'),
  ('CEG', 'Constellation Energy Corporatio', 'stock', 'standard', 'common', 'fmp', 'CEG'),
  ('CF', 'CF Industries Holdings, Inc.', 'stock', 'standard', 'common', 'fmp', 'CF'),
  ('CFG', 'Citizens Financial Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'CFG'),
  ('CHD', 'Church & Dwight Company, Inc.', 'stock', 'standard', 'common', 'fmp', 'CHD'),
  ('CHRW', 'C.H. Robinson Worldwide, Inc.', 'stock', 'standard', 'common', 'fmp', 'CHRW'),
  ('CHTR', 'Charter Communications, Inc.', 'stock', 'standard', 'common', 'fmp', 'CHTR'),
  ('CI', 'The Cigna Group', 'stock', 'standard', 'common', 'fmp', 'CI'),
  ('CIEN', 'Ciena Corporation', 'stock', 'standard', 'common', 'fmp', 'CIEN'),
  ('CINF', 'Cincinnati Financial Corporatio', 'stock', 'standard', 'common', 'fmp', 'CINF'),
  ('CL', 'Colgate-Palmolive Company', 'stock', 'standard', 'common', 'fmp', 'CL'),
  ('CLX', 'Clorox Company (The)', 'stock', 'standard', 'common', 'fmp', 'CLX'),
  ('CMCSA', 'Comcast Corporation', 'stock', 'standard', 'common', 'fmp', 'CMCSA'),
  ('CME', 'CME Group Inc.', 'stock', 'standard', 'common', 'fmp', 'CME'),
  ('CMG', 'Chipotle Mexican Grill, Inc.', 'stock', 'standard', 'common', 'fmp', 'CMG'),
  ('CMI', 'Cummins Inc.', 'stock', 'standard', 'common', 'fmp', 'CMI'),
  ('CMS', 'CMS Energy Corporation', 'stock', 'standard', 'common', 'fmp', 'CMS'),
  ('CNC', 'Centene Corporation', 'stock', 'standard', 'common', 'fmp', 'CNC'),
  ('CNP', 'CenterPoint Energy, Inc (Holdin', 'stock', 'standard', 'common', 'fmp', 'CNP'),
  ('COF', 'Capital One Financial Corporati', 'stock', 'standard', 'common', 'fmp', 'COF'),
  ('COHR', 'Coherent Corp.', 'stock', 'standard', 'common', 'fmp', 'COHR'),
  ('COIN', 'Coinbase Global, Inc.', 'stock', 'standard', 'common', 'fmp', 'COIN'),
  ('COO', 'The Cooper Companies, Inc.', 'stock', 'standard', 'common', 'fmp', 'COO'),
  ('COP', 'ConocoPhillips', 'stock', 'standard', 'common', 'fmp', 'COP'),
  ('COR', 'Cencora, Inc.', 'stock', 'standard', 'common', 'fmp', 'COR'),
  ('COST', 'Costco Wholesale Corporation', 'stock', 'standard', 'common', 'fmp', 'COST'),
  ('CPAY', 'Corpay, Inc.', 'stock', 'standard', 'common', 'fmp', 'CPAY'),
  ('CPRT', 'Copart, Inc.', 'stock', 'standard', 'common', 'fmp', 'CPRT'),
  ('CPT', 'Camden Property Trust', 'stock', 'standard', 'common', 'fmp', 'CPT'),
  ('CRH', 'CRH PLC', 'stock', 'standard', 'common', 'fmp', 'CRH'),
  ('CRL', 'Charles River Laboratories Inte', 'stock', 'standard', 'common', 'fmp', 'CRL'),
  ('CRM', 'Salesforce, Inc.', 'stock', 'standard', 'common', 'fmp', 'CRM'),
  ('CRWD', 'CrowdStrike Holdings, Inc.', 'stock', 'standard', 'common', 'fmp', 'CRWD'),
  ('CSCO', 'Cisco Systems, Inc.', 'stock', 'standard', 'common', 'fmp', 'CSCO'),
  ('CSGP', 'CoStar Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'CSGP'),
  ('CSX', 'CSX Corporation', 'stock', 'standard', 'common', 'fmp', 'CSX'),
  ('CTAS', 'Cintas Corporation', 'stock', 'standard', 'common', 'fmp', 'CTAS'),
  ('CTSH', 'Cognizant Technology Solutions', 'stock', 'standard', 'common', 'fmp', 'CTSH'),
  ('CTVA', 'Corteva, Inc.', 'stock', 'standard', 'common', 'fmp', 'CTVA'),
  ('CVNA', 'Carvana Co.', 'stock', 'standard', 'common', 'fmp', 'CVNA'),
  ('CVS', 'CVS Health Corporation', 'stock', 'standard', 'common', 'fmp', 'CVS'),
  ('CVX', 'Chevron Corporation', 'stock', 'standard', 'common', 'fmp', 'CVX'),
  ('D', 'Dominion Energy, Inc.', 'stock', 'standard', 'common', 'fmp', 'D'),
  ('DAL', 'Delta Air Lines, Inc.', 'stock', 'standard', 'common', 'fmp', 'DAL'),
  ('DASH', 'DoorDash, Inc.', 'stock', 'standard', 'common', 'fmp', 'DASH'),
  ('DD', 'DuPont de Nemours, Inc.', 'stock', 'standard', 'common', 'fmp', 'DD'),
  ('DDOG', 'Datadog, Inc.', 'stock', 'standard', 'common', 'fmp', 'DDOG'),
  ('DE', 'Deere & Company', 'stock', 'standard', 'common', 'fmp', 'DE'),
  ('DECK', 'Deckers Outdoor Corporation', 'stock', 'standard', 'common', 'fmp', 'DECK'),
  ('DELL', 'Dell Technologies Inc.', 'stock', 'standard', 'common', 'fmp', 'DELL'),
  ('DG', 'Dollar General Corporation', 'stock', 'standard', 'common', 'fmp', 'DG'),
  ('DGX', 'Quest Diagnostics Incorporated', 'stock', 'standard', 'common', 'fmp', 'DGX'),
  ('DHI', 'D.R. Horton, Inc.', 'stock', 'standard', 'common', 'fmp', 'DHI'),
  ('DHR', 'Danaher Corporation', 'stock', 'standard', 'common', 'fmp', 'DHR'),
  ('DIS', 'Walt Disney Company (The)', 'stock', 'standard', 'common', 'fmp', 'DIS'),
  ('DLR', 'Digital Realty Trust, Inc.', 'stock', 'standard', 'common', 'fmp', 'DLR'),
  ('DLTR', 'Dollar Tree, Inc.', 'stock', 'standard', 'common', 'fmp', 'DLTR'),
  ('DOC', 'Healthpeak Properties, Inc.', 'stock', 'standard', 'common', 'fmp', 'DOC'),
  ('DOV', 'Dover Corporation', 'stock', 'standard', 'common', 'fmp', 'DOV'),
  ('DOW', 'Dow Inc.', 'stock', 'standard', 'common', 'fmp', 'DOW'),
  ('DPZ', 'Domino''s Pizza Inc', 'stock', 'standard', 'common', 'fmp', 'DPZ'),
  ('DRI', 'Darden Restaurants, Inc.', 'stock', 'standard', 'common', 'fmp', 'DRI'),
  ('DTE', 'DTE Energy Company', 'stock', 'standard', 'common', 'fmp', 'DTE'),
  ('DUK', 'Duke Energy Corporation (Holdin', 'stock', 'standard', 'common', 'fmp', 'DUK'),
  ('DVA', 'DaVita Inc.', 'stock', 'standard', 'common', 'fmp', 'DVA'),
  ('DVN', 'Devon Energy Corporation', 'stock', 'standard', 'common', 'fmp', 'DVN'),
  ('DXCM', 'DexCom, Inc.', 'stock', 'standard', 'common', 'fmp', 'DXCM'),
  ('EA', 'Electronic Arts Inc.', 'stock', 'standard', 'common', 'fmp', 'EA'),
  ('EBAY', 'eBay Inc.', 'stock', 'standard', 'common', 'fmp', 'EBAY'),
  ('ECHO', 'EchoStar Corporation', 'stock', 'standard', 'common', 'fmp', 'ECHO'),
  ('ECL', 'Ecolab Inc.', 'stock', 'standard', 'common', 'fmp', 'ECL'),
  ('ED', 'Consolidated Edison, Inc.', 'stock', 'standard', 'common', 'fmp', 'ED'),
  ('EFX', 'Equifax, Inc.', 'stock', 'standard', 'common', 'fmp', 'EFX'),
  ('EG', 'Everest Group, Ltd.', 'stock', 'standard', 'common', 'fmp', 'EG'),
  ('EIX', 'Edison International', 'stock', 'standard', 'common', 'fmp', 'EIX'),
  ('EL', 'Estee Lauder Companies, Inc. (T', 'stock', 'standard', 'common', 'fmp', 'EL'),
  ('ELV', 'Elevance Health, Inc.', 'stock', 'standard', 'common', 'fmp', 'ELV'),
  ('EME', 'EMCOR Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'EME'),
  ('EMR', 'Emerson Electric Company', 'stock', 'standard', 'common', 'fmp', 'EMR'),
  ('EOG', 'EOG Resources, Inc.', 'stock', 'standard', 'common', 'fmp', 'EOG'),
  ('EQIX', 'Equinix, Inc.', 'stock', 'standard', 'common', 'fmp', 'EQIX'),
  ('EQR', 'Equity Residential', 'stock', 'standard', 'common', 'fmp', 'EQR'),
  ('EQT', 'EQT Corporation', 'stock', 'standard', 'common', 'fmp', 'EQT'),
  ('ERIE', 'Erie Indemnity Company', 'stock', 'standard', 'common', 'fmp', 'ERIE'),
  ('ES', 'Eversource Energy (D/B/A)', 'stock', 'standard', 'common', 'fmp', 'ES'),
  ('ESS', 'Essex Property Trust, Inc.', 'stock', 'standard', 'common', 'fmp', 'ESS'),
  ('ETN', 'Eaton Corporation, PLC', 'stock', 'standard', 'common', 'fmp', 'ETN'),
  ('ETR', 'Entergy Corporation', 'stock', 'standard', 'common', 'fmp', 'ETR'),
  ('EVRG', 'Evergy, Inc.', 'stock', 'standard', 'common', 'fmp', 'EVRG'),
  ('EW', 'Edwards Lifesciences Corporatio', 'stock', 'standard', 'common', 'fmp', 'EW'),
  ('EXC', 'Exelon Corporation', 'stock', 'standard', 'common', 'fmp', 'EXC'),
  ('EXE', 'Expand Energy Corporation', 'stock', 'standard', 'common', 'fmp', 'EXE'),
  ('EXPD', 'Expeditors International of Was', 'stock', 'standard', 'common', 'fmp', 'EXPD'),
  ('EXPE', 'Expedia Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'EXPE'),
  ('EXR', 'Extra Space Storage Inc', 'stock', 'standard', 'common', 'fmp', 'EXR'),
  ('F', 'Ford Motor Company', 'stock', 'standard', 'common', 'fmp', 'F'),
  ('FANG', 'Diamondback Energy, Inc.', 'stock', 'standard', 'common', 'fmp', 'FANG'),
  ('FAST', 'Fastenal Company', 'stock', 'standard', 'common', 'fmp', 'FAST'),
  ('FCX', 'Freeport-McMoRan, Inc.', 'stock', 'standard', 'common', 'fmp', 'FCX'),
  ('FDS', 'FactSet Research Systems Inc.', 'stock', 'standard', 'common', 'fmp', 'FDS'),
  ('FDX', 'FedEx Corporation', 'stock', 'standard', 'common', 'fmp', 'FDX'),
  ('FDXF', 'FedEx Freight Holding Company,', 'stock', 'standard', 'common', 'fmp', 'FDXF'),
  ('FE', 'FirstEnergy Corp.', 'stock', 'standard', 'common', 'fmp', 'FE'),
  ('FFIV', 'F5, Inc.', 'stock', 'standard', 'common', 'fmp', 'FFIV'),
  ('FICO', 'Fair Isaac Corporation', 'stock', 'standard', 'common', 'fmp', 'FICO'),
  ('FIS', 'Fidelity National Information S', 'stock', 'standard', 'common', 'fmp', 'FIS'),
  ('FISV', 'Fiserv, Inc.', 'stock', 'standard', 'common', 'fmp', 'FISV'),
  ('FITB', 'Fifth Third Bancorp', 'stock', 'standard', 'common', 'fmp', 'FITB'),
  ('FIX', 'Comfort Systems USA, Inc.', 'stock', 'standard', 'common', 'fmp', 'FIX'),
  ('FLEX', 'Flex Ltd.', 'stock', 'standard', 'common', 'fmp', 'FLEX'),
  ('FOX', 'Fox Corporation', 'stock', 'standard', 'common', 'fmp', 'FOX'),
  ('FOXA', 'Fox Corporation', 'stock', 'standard', 'common', 'fmp', 'FOXA'),
  ('FRT', 'Federal Realty Investment Trust', 'stock', 'standard', 'common', 'fmp', 'FRT'),
  ('FSLR', 'First Solar, Inc.', 'stock', 'standard', 'common', 'fmp', 'FSLR'),
  ('FTNT', 'Fortinet, Inc.', 'stock', 'standard', 'common', 'fmp', 'FTNT'),
  ('FTV', 'Fortive Corporation', 'stock', 'standard', 'common', 'fmp', 'FTV'),
  ('GD', 'General Dynamics Corporation', 'stock', 'standard', 'common', 'fmp', 'GD'),
  ('GDDY', 'GoDaddy Inc.', 'stock', 'standard', 'common', 'fmp', 'GDDY'),
  ('GE', 'GE Aerospace', 'stock', 'standard', 'common', 'fmp', 'GE'),
  ('GEHC', 'GE HealthCare Technologies Inc.', 'stock', 'standard', 'common', 'fmp', 'GEHC'),
  ('GEN', 'Gen Digital Inc.', 'stock', 'standard', 'common', 'fmp', 'GEN'),
  ('GEV', 'GE Vernova Inc.', 'stock', 'standard', 'common', 'fmp', 'GEV'),
  ('GILD', 'Gilead Sciences, Inc.', 'stock', 'standard', 'common', 'fmp', 'GILD'),
  ('GIS', 'General Mills, Inc.', 'stock', 'standard', 'common', 'fmp', 'GIS'),
  ('GL', 'Globe Life Inc.', 'stock', 'standard', 'common', 'fmp', 'GL'),
  ('GLW', 'Corning Incorporated', 'stock', 'standard', 'common', 'fmp', 'GLW'),
  ('GM', 'General Motors Company', 'stock', 'standard', 'common', 'fmp', 'GM'),
  ('GNRC', 'Generac Holdlings Inc.', 'stock', 'standard', 'common', 'fmp', 'GNRC'),
  ('GOOG', 'Alphabet Inc.', 'stock', 'standard', 'common', 'fmp', 'GOOG'),
  ('GOOGL', 'Alphabet Inc.', 'stock', 'standard', 'common', 'fmp', 'GOOGL'),
  ('GPC', 'Genuine Parts Company', 'stock', 'standard', 'common', 'fmp', 'GPC'),
  ('GPN', 'Global Payments Inc.', 'stock', 'standard', 'common', 'fmp', 'GPN'),
  ('GRMN', 'Garmin Ltd.', 'stock', 'standard', 'common', 'fmp', 'GRMN'),
  ('GS', 'Goldman Sachs Group, Inc. (The)', 'stock', 'standard', 'common', 'fmp', 'GS'),
  ('GWW', 'W.W. Grainger, Inc.', 'stock', 'standard', 'common', 'fmp', 'GWW'),
  ('HAL', 'Halliburton Company', 'stock', 'standard', 'common', 'fmp', 'HAL'),
  ('HAS', 'Hasbro, Inc.', 'stock', 'standard', 'common', 'fmp', 'HAS'),
  ('HBAN', 'Huntington Bancshares Incorpora', 'stock', 'standard', 'common', 'fmp', 'HBAN'),
  ('HCA', 'HCA Healthcare, Inc.', 'stock', 'standard', 'common', 'fmp', 'HCA'),
  ('HD', 'Home Depot, Inc. (The)', 'stock', 'standard', 'common', 'fmp', 'HD'),
  ('HIG', 'The Hartford Insurance Group, I', 'stock', 'standard', 'common', 'fmp', 'HIG'),
  ('HII', 'Huntington Ingalls Industries,', 'stock', 'standard', 'common', 'fmp', 'HII'),
  ('HLT', 'Hilton Worldwide Holdings Inc.', 'stock', 'standard', 'common', 'fmp', 'HLT'),
  ('HON', 'Honeywell International Inc.', 'stock', 'standard', 'common', 'fmp', 'HON'),
  ('HONA', 'Honeywell Aerospace Inc.', 'stock', 'standard', 'common', 'fmp', 'HONA'),
  ('HOOD', 'Robinhood Markets, Inc.', 'stock', 'standard', 'common', 'fmp', 'HOOD'),
  ('HPE', 'Hewlett Packard Enterprise Comp', 'stock', 'standard', 'common', 'fmp', 'HPE'),
  ('HPQ', 'HP Inc.', 'stock', 'standard', 'common', 'fmp', 'HPQ'),
  ('HRL', 'Hormel Foods Corporation', 'stock', 'standard', 'common', 'fmp', 'HRL'),
  ('HSIC', 'Henry Schein, Inc.', 'stock', 'standard', 'common', 'fmp', 'HSIC'),
  ('HST', 'Host Hotels & Resorts, Inc.', 'stock', 'standard', 'common', 'fmp', 'HST'),
  ('HSY', 'The Hershey Company', 'stock', 'standard', 'common', 'fmp', 'HSY'),
  ('HUBB', 'Hubbell Inc', 'stock', 'standard', 'common', 'fmp', 'HUBB'),
  ('HUM', 'Humana Inc.', 'stock', 'standard', 'common', 'fmp', 'HUM'),
  ('HWM', 'Howmet Aerospace Inc.', 'stock', 'standard', 'common', 'fmp', 'HWM'),
  ('IBKR', 'Interactive Brokers Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'IBKR'),
  ('IBM', 'International Business Machines', 'stock', 'standard', 'common', 'fmp', 'IBM'),
  ('ICE', 'Intercontinental Exchange Inc.', 'stock', 'standard', 'common', 'fmp', 'ICE'),
  ('IDXX', 'IDEXX Laboratories, Inc.', 'stock', 'standard', 'common', 'fmp', 'IDXX'),
  ('IEX', 'IDEX Corporation', 'stock', 'standard', 'common', 'fmp', 'IEX'),
  ('IFF', 'International Flavors & Fragran', 'stock', 'standard', 'common', 'fmp', 'IFF'),
  ('INCY', 'Incyte Corporation', 'stock', 'standard', 'common', 'fmp', 'INCY'),
  ('INTC', 'Intel Corporation', 'stock', 'standard', 'common', 'fmp', 'INTC'),
  ('INTU', 'Intuit Inc.', 'stock', 'standard', 'common', 'fmp', 'INTU'),
  ('INVH', 'Invitation Homes Inc.', 'stock', 'standard', 'common', 'fmp', 'INVH'),
  ('IP', 'International Paper Company', 'stock', 'standard', 'common', 'fmp', 'IP'),
  ('IQV', 'IQVIA Holdings, Inc.', 'stock', 'standard', 'common', 'fmp', 'IQV'),
  ('IR', 'Ingersoll Rand Inc.', 'stock', 'standard', 'common', 'fmp', 'IR'),
  ('IRM', 'Iron Mountain Incorporated (Del', 'stock', 'standard', 'common', 'fmp', 'IRM'),
  ('ISRG', 'Intuitive Surgical, Inc.', 'stock', 'standard', 'common', 'fmp', 'ISRG'),
  ('IT', 'Gartner, Inc.', 'stock', 'standard', 'common', 'fmp', 'IT'),
  ('ITW', 'Illinois Tool Works Inc.', 'stock', 'standard', 'common', 'fmp', 'ITW'),
  ('IVZ', 'Invesco Ltd', 'stock', 'standard', 'common', 'fmp', 'IVZ'),
  ('J', 'Jacobs Solutions Inc.', 'stock', 'standard', 'common', 'fmp', 'J'),
  ('JBHT', 'J.B. Hunt Transport Services, I', 'stock', 'standard', 'common', 'fmp', 'JBHT'),
  ('JBL', 'Jabil Inc.', 'stock', 'standard', 'common', 'fmp', 'JBL'),
  ('JCI', 'Johnson Controls International', 'stock', 'standard', 'common', 'fmp', 'JCI'),
  ('JKHY', 'Jack Henry & Associates, Inc.', 'stock', 'standard', 'common', 'fmp', 'JKHY'),
  ('JNJ', 'Johnson & Johnson', 'stock', 'standard', 'common', 'fmp', 'JNJ'),
  ('JPM', 'JP Morgan Chase & Co.', 'stock', 'standard', 'common', 'fmp', 'JPM'),
  ('KDP', 'Keurig Dr Pepper Inc.', 'stock', 'standard', 'common', 'fmp', 'KDP'),
  ('KEY', 'KeyCorp', 'stock', 'standard', 'common', 'fmp', 'KEY'),
  ('KEYS', 'Keysight Technologies Inc.', 'stock', 'standard', 'common', 'fmp', 'KEYS'),
  ('KHC', 'The Kraft Heinz Company', 'stock', 'standard', 'common', 'fmp', 'KHC'),
  ('KIM', 'Kimco Realty Corporation (HC)', 'stock', 'standard', 'common', 'fmp', 'KIM'),
  ('KKR', 'KKR & Co. Inc.', 'stock', 'standard', 'common', 'fmp', 'KKR'),
  ('KLAC', 'KLA Corporation', 'stock', 'standard', 'common', 'fmp', 'KLAC'),
  ('KMB', 'Kimberly-Clark Corporation', 'stock', 'standard', 'common', 'fmp', 'KMB'),
  ('KMI', 'Kinder Morgan, Inc.', 'stock', 'standard', 'common', 'fmp', 'KMI'),
  ('KO', 'Coca-Cola Company (The)', 'stock', 'standard', 'common', 'fmp', 'KO'),
  ('KR', 'Kroger Company (The)', 'stock', 'standard', 'common', 'fmp', 'KR'),
  ('KVUE', 'Kenvue Inc.', 'stock', 'standard', 'common', 'fmp', 'KVUE'),
  ('L', 'Loews Corporation', 'stock', 'standard', 'common', 'fmp', 'L'),
  ('LDOS', 'Leidos Holdings, Inc.', 'stock', 'standard', 'common', 'fmp', 'LDOS'),
  ('LEN', 'Lennar Corporation', 'stock', 'standard', 'common', 'fmp', 'LEN'),
  ('LH', 'Labcorp Holdings Inc.', 'stock', 'standard', 'common', 'fmp', 'LH'),
  ('LHX', 'L3Harris Technologies, Inc.', 'stock', 'standard', 'common', 'fmp', 'LHX'),
  ('LII', 'Lennox International, Inc.', 'stock', 'standard', 'common', 'fmp', 'LII'),
  ('LIN', 'Linde plc', 'stock', 'standard', 'common', 'fmp', 'LIN'),
  ('LITE', 'Lumentum Holdings Inc.', 'stock', 'standard', 'common', 'fmp', 'LITE'),
  ('LLY', 'Eli Lilly and Company', 'stock', 'standard', 'common', 'fmp', 'LLY'),
  ('LMT', 'Lockheed Martin Corporation', 'stock', 'standard', 'common', 'fmp', 'LMT'),
  ('LNT', 'Alliant Energy Corporation', 'stock', 'standard', 'common', 'fmp', 'LNT'),
  ('LOW', 'Lowe''s Companies, Inc.', 'stock', 'standard', 'common', 'fmp', 'LOW'),
  ('LRCX', 'Lam Research Corporation', 'stock', 'standard', 'common', 'fmp', 'LRCX'),
  ('LULU', 'lululemon athletica inc.', 'stock', 'standard', 'common', 'fmp', 'LULU'),
  ('LUV', 'Southwest Airlines Company', 'stock', 'standard', 'common', 'fmp', 'LUV'),
  ('LVS', 'Las Vegas Sands Corp.', 'stock', 'standard', 'common', 'fmp', 'LVS'),
  ('LYB', 'LyondellBasell Industries NV', 'stock', 'standard', 'common', 'fmp', 'LYB'),
  ('LYV', 'Live Nation Entertainment, Inc.', 'stock', 'standard', 'common', 'fmp', 'LYV'),
  ('MA', 'Mastercard Incorporated', 'stock', 'standard', 'common', 'fmp', 'MA'),
  ('MAA', 'Mid-America Apartment Communiti', 'stock', 'standard', 'common', 'fmp', 'MAA'),
  ('MAR', 'Marriott International', 'stock', 'standard', 'common', 'fmp', 'MAR'),
  ('MAS', 'Masco Corporation', 'stock', 'standard', 'common', 'fmp', 'MAS'),
  ('MCD', 'McDonald''s Corporation', 'stock', 'standard', 'common', 'fmp', 'MCD'),
  ('MCHP', 'Microchip Technology Incorporat', 'stock', 'standard', 'common', 'fmp', 'MCHP'),
  ('MCK', 'McKesson Corporation', 'stock', 'standard', 'common', 'fmp', 'MCK'),
  ('MCO', 'Moody''s Corporation', 'stock', 'standard', 'common', 'fmp', 'MCO'),
  ('MDLZ', 'Mondelez International, Inc.', 'stock', 'standard', 'common', 'fmp', 'MDLZ'),
  ('MDT', 'Medtronic plc.', 'stock', 'standard', 'common', 'fmp', 'MDT'),
  ('MET', 'MetLife, Inc.', 'stock', 'standard', 'common', 'fmp', 'MET'),
  ('META', 'Meta Platforms, Inc.', 'stock', 'standard', 'common', 'fmp', 'META'),
  ('MGM', 'MGM Resorts International', 'stock', 'standard', 'common', 'fmp', 'MGM'),
  ('MKC', 'McCormick & Company, Incorporat', 'stock', 'standard', 'common', 'fmp', 'MKC'),
  ('MLM', 'Martin Marietta Materials, Inc.', 'stock', 'standard', 'common', 'fmp', 'MLM'),
  ('MMM', '3M Company', 'stock', 'standard', 'common', 'fmp', 'MMM'),
  ('MNST', 'Monster Beverage Corporation', 'stock', 'standard', 'common', 'fmp', 'MNST'),
  ('MO', 'Altria Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'MO'),
  ('MOS', 'Mosaic Company (The)', 'stock', 'standard', 'common', 'fmp', 'MOS'),
  ('MPC', 'Marathon Petroleum Corporation', 'stock', 'standard', 'common', 'fmp', 'MPC'),
  ('MPWR', 'Monolithic Power Systems, Inc.', 'stock', 'standard', 'common', 'fmp', 'MPWR'),
  ('MRK', 'Merck & Company, Inc.', 'stock', 'standard', 'common', 'fmp', 'MRK'),
  ('MRNA', 'Moderna, Inc.', 'stock', 'standard', 'common', 'fmp', 'MRNA'),
  ('MRSH', 'Marsh', 'stock', 'standard', 'common', 'fmp', 'MRSH'),
  ('MRVL', 'Marvell Technology, Inc.', 'stock', 'standard', 'common', 'fmp', 'MRVL'),
  ('MS', 'Morgan Stanley', 'stock', 'standard', 'common', 'fmp', 'MS'),
  ('MSCI', 'MSCI Inc.', 'stock', 'standard', 'common', 'fmp', 'MSCI'),
  ('MSFT', 'Microsoft Corporation', 'stock', 'standard', 'common', 'fmp', 'MSFT'),
  ('MSI', 'Motorola Solutions, Inc.', 'stock', 'standard', 'common', 'fmp', 'MSI'),
  ('MTB', 'M&T Bank Corporation', 'stock', 'standard', 'common', 'fmp', 'MTB'),
  ('MTD', 'Mettler-Toledo International, I', 'stock', 'standard', 'common', 'fmp', 'MTD'),
  ('MU', 'Micron Technology, Inc.', 'stock', 'standard', 'common', 'fmp', 'MU'),
  ('NCLH', 'Norwegian Cruise Line Holdings', 'stock', 'standard', 'common', 'fmp', 'NCLH'),
  ('NDAQ', 'Nasdaq, Inc.', 'stock', 'standard', 'common', 'fmp', 'NDAQ'),
  ('NDSN', 'Nordson Corporation', 'stock', 'standard', 'common', 'fmp', 'NDSN'),
  ('NEE', 'NextEra Energy, Inc.', 'stock', 'standard', 'common', 'fmp', 'NEE'),
  ('NEM', 'Newmont Corporation', 'stock', 'standard', 'common', 'fmp', 'NEM'),
  ('NFLX', 'Netflix, Inc.', 'stock', 'standard', 'common', 'fmp', 'NFLX'),
  ('NI', 'NiSource Inc', 'stock', 'standard', 'common', 'fmp', 'NI'),
  ('NKE', 'Nike, Inc.', 'stock', 'standard', 'common', 'fmp', 'NKE'),
  ('NOC', 'Northrop Grumman Corporation', 'stock', 'standard', 'common', 'fmp', 'NOC'),
  ('NOW', 'ServiceNow, Inc.', 'stock', 'standard', 'common', 'fmp', 'NOW'),
  ('NRG', 'NRG Energy, Inc.', 'stock', 'standard', 'common', 'fmp', 'NRG'),
  ('NSC', 'Norfolk Southern Corporation', 'stock', 'standard', 'common', 'fmp', 'NSC'),
  ('NTAP', 'NetApp, Inc.', 'stock', 'standard', 'common', 'fmp', 'NTAP'),
  ('NTRS', 'Northern Trust Corporation', 'stock', 'standard', 'common', 'fmp', 'NTRS'),
  ('NUE', 'Nucor Corporation', 'stock', 'standard', 'common', 'fmp', 'NUE'),
  ('NVDA', 'NVIDIA Corporation', 'stock', 'standard', 'common', 'fmp', 'NVDA'),
  ('NVR', 'NVR, Inc.', 'stock', 'standard', 'common', 'fmp', 'NVR'),
  ('NWS', 'News Corporation', 'stock', 'standard', 'common', 'fmp', 'NWS'),
  ('NWSA', 'News Corporation', 'stock', 'standard', 'common', 'fmp', 'NWSA'),
  ('NXPI', 'NXP Semiconductors N.V.', 'stock', 'standard', 'common', 'fmp', 'NXPI'),
  ('O', 'Realty Income Corporation', 'stock', 'standard', 'common', 'fmp', 'O'),
  ('ODFL', 'Old Dominion Freight Line, Inc.', 'stock', 'standard', 'common', 'fmp', 'ODFL'),
  ('OKE', 'ONEOK, Inc.', 'stock', 'standard', 'common', 'fmp', 'OKE'),
  ('OMC', 'Omnicom Group Inc.', 'stock', 'standard', 'common', 'fmp', 'OMC'),
  ('ON', 'ON Semiconductor Corporation', 'stock', 'standard', 'common', 'fmp', 'ON'),
  ('ORCL', 'Oracle Corporation', 'stock', 'standard', 'common', 'fmp', 'ORCL'),
  ('ORLY', 'O''Reilly Automotive, Inc.', 'stock', 'standard', 'common', 'fmp', 'ORLY'),
  ('OTIS', 'Otis Worldwide Corporation', 'stock', 'standard', 'common', 'fmp', 'OTIS'),
  ('OXY', 'Occidental Petroleum Corporatio', 'stock', 'standard', 'common', 'fmp', 'OXY'),
  ('PANW', 'Palo Alto Networks, Inc.', 'stock', 'standard', 'common', 'fmp', 'PANW'),
  ('PAYX', 'Paychex, Inc.', 'stock', 'standard', 'common', 'fmp', 'PAYX'),
  ('PCAR', 'PACCAR Inc.', 'stock', 'standard', 'common', 'fmp', 'PCAR'),
  ('PCG', 'Pacific Gas & Electric Co.', 'stock', 'standard', 'common', 'fmp', 'PCG'),
  ('PEG', 'Public Service Enterprise Group', 'stock', 'standard', 'common', 'fmp', 'PEG'),
  ('PEP', 'Pepsico, Inc.', 'stock', 'standard', 'common', 'fmp', 'PEP'),
  ('PFE', 'Pfizer, Inc.', 'stock', 'standard', 'common', 'fmp', 'PFE'),
  ('PFG', 'Principal Financial Group Inc', 'stock', 'standard', 'common', 'fmp', 'PFG'),
  ('PG', 'Procter & Gamble Company (The)', 'stock', 'standard', 'common', 'fmp', 'PG'),
  ('PGR', 'Progressive Corporation (The)', 'stock', 'standard', 'common', 'fmp', 'PGR'),
  ('PH', 'Parker-Hannifin Corporation', 'stock', 'standard', 'common', 'fmp', 'PH'),
  ('PHM', 'PulteGroup, Inc.', 'stock', 'standard', 'common', 'fmp', 'PHM'),
  ('PKG', 'Packaging Corporation of Americ', 'stock', 'standard', 'common', 'fmp', 'PKG'),
  ('PLD', 'Prologis, Inc.', 'stock', 'standard', 'common', 'fmp', 'PLD'),
  ('PLTR', 'Palantir Technologies Inc.', 'stock', 'standard', 'common', 'fmp', 'PLTR'),
  ('PM', 'Philip Morris International Inc', 'stock', 'standard', 'common', 'fmp', 'PM'),
  ('PNC', 'PNC Financial Services Group, I', 'stock', 'standard', 'common', 'fmp', 'PNC'),
  ('PNR', 'Pentair plc.', 'stock', 'standard', 'common', 'fmp', 'PNR'),
  ('PNW', 'Pinnacle West Capital Corporati', 'stock', 'standard', 'common', 'fmp', 'PNW'),
  ('PODD', 'Insulet Corporation', 'stock', 'standard', 'common', 'fmp', 'PODD'),
  ('PPG', 'PPG Industries, Inc.', 'stock', 'standard', 'common', 'fmp', 'PPG'),
  ('PPL', 'PPL Corporation', 'stock', 'standard', 'common', 'fmp', 'PPL'),
  ('PRU', 'Prudential Financial, Inc.', 'stock', 'standard', 'common', 'fmp', 'PRU'),
  ('PSA', 'Public Storage', 'stock', 'standard', 'common', 'fmp', 'PSA'),
  ('PSKY', 'Paramount Skydance Corporation', 'stock', 'standard', 'common', 'fmp', 'PSKY'),
  ('PSX', 'Phillips 66', 'stock', 'standard', 'common', 'fmp', 'PSX'),
  ('PTC', 'PTC Inc.', 'stock', 'standard', 'common', 'fmp', 'PTC'),
  ('PWR', 'Quanta Services, Inc.', 'stock', 'standard', 'common', 'fmp', 'PWR'),
  ('PYPL', 'PayPal Holdings, Inc.', 'stock', 'standard', 'common', 'fmp', 'PYPL'),
  ('Q', 'Qnity Electronics, Inc.', 'stock', 'standard', 'common', 'fmp', 'Q'),
  ('QCOM', 'QUALCOMM Incorporated', 'stock', 'standard', 'common', 'fmp', 'QCOM'),
  ('RCL', 'Royal Caribbean Cruises Ltd.', 'stock', 'standard', 'common', 'fmp', 'RCL'),
  ('REG', 'Regency Centers Corporation', 'stock', 'standard', 'common', 'fmp', 'REG'),
  ('REGN', 'Regeneron Pharmaceuticals, Inc.', 'stock', 'standard', 'common', 'fmp', 'REGN'),
  ('RF', 'Regions Financial Corporation', 'stock', 'standard', 'common', 'fmp', 'RF'),
  ('RJF', 'Raymond James Financial, Inc.', 'stock', 'standard', 'common', 'fmp', 'RJF'),
  ('RL', 'Ralph Lauren Corporation', 'stock', 'standard', 'common', 'fmp', 'RL'),
  ('RMD', 'ResMed Inc.', 'stock', 'standard', 'common', 'fmp', 'RMD'),
  ('ROK', 'Rockwell Automation, Inc.', 'stock', 'standard', 'common', 'fmp', 'ROK'),
  ('ROL', 'Rollins, Inc.', 'stock', 'standard', 'common', 'fmp', 'ROL'),
  ('ROP', 'Roper Technologies, Inc.', 'stock', 'standard', 'common', 'fmp', 'ROP'),
  ('ROST', 'Ross Stores, Inc.', 'stock', 'standard', 'common', 'fmp', 'ROST'),
  ('RSG', 'Republic Services, Inc.', 'stock', 'standard', 'common', 'fmp', 'RSG'),
  ('RTX', 'RTX Corporation', 'stock', 'standard', 'common', 'fmp', 'RTX'),
  ('RVTY', 'Revvity, Inc.', 'stock', 'standard', 'common', 'fmp', 'RVTY'),
  ('SBAC', 'SBA Communications Corporation', 'stock', 'standard', 'common', 'fmp', 'SBAC'),
  ('SBUX', 'Starbucks Corporation', 'stock', 'standard', 'common', 'fmp', 'SBUX'),
  ('SCHW', 'Charles Schwab Corporation (The', 'stock', 'standard', 'common', 'fmp', 'SCHW'),
  ('SHW', 'Sherwin-Williams Company (The)', 'stock', 'standard', 'common', 'fmp', 'SHW'),
  ('SJM', 'The J.M. Smucker Company', 'stock', 'standard', 'common', 'fmp', 'SJM'),
  ('SLB', 'SLB Limited', 'stock', 'standard', 'common', 'fmp', 'SLB'),
  ('SMCI', 'Super Micro Computer, Inc.', 'stock', 'standard', 'common', 'fmp', 'SMCI'),
  ('SNA', 'Snap-On Incorporated', 'stock', 'standard', 'common', 'fmp', 'SNA'),
  ('SNDK', 'Sandisk Corporation', 'stock', 'standard', 'common', 'fmp', 'SNDK'),
  ('SNPS', 'Synopsys, Inc.', 'stock', 'standard', 'common', 'fmp', 'SNPS'),
  ('SO', 'Southern Company (The)', 'stock', 'standard', 'common', 'fmp', 'SO'),
  ('SOLV', 'Solventum Corporation', 'stock', 'standard', 'common', 'fmp', 'SOLV'),
  ('SPG', 'Simon Property Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'SPG'),
  ('SPGI', 'S&P Global Inc.', 'stock', 'standard', 'common', 'fmp', 'SPGI'),
  ('SRE', 'DBA Sempra', 'stock', 'standard', 'common', 'fmp', 'SRE'),
  ('STE', 'STERIS plc (Ireland)', 'stock', 'standard', 'common', 'fmp', 'STE'),
  ('STLD', 'Steel Dynamics, Inc.', 'stock', 'standard', 'common', 'fmp', 'STLD'),
  ('STT', 'State Street Corporation', 'stock', 'standard', 'common', 'fmp', 'STT'),
  ('STX', 'Seagate Technology Holdings PLC', 'stock', 'standard', 'common', 'fmp', 'STX'),
  ('STZ', 'Constellation Brands, Inc.', 'stock', 'standard', 'common', 'fmp', 'STZ'),
  ('SW', 'Smurfit WestRock plc', 'stock', 'standard', 'common', 'fmp', 'SW'),
  ('SWK', 'Stanley Black & Decker, Inc.', 'stock', 'standard', 'common', 'fmp', 'SWK'),
  ('SWKS', 'Skyworks Solutions, Inc.', 'stock', 'standard', 'common', 'fmp', 'SWKS'),
  ('SYF', 'Synchrony Financial', 'stock', 'standard', 'common', 'fmp', 'SYF'),
  ('SYK', 'Stryker Corporation', 'stock', 'standard', 'common', 'fmp', 'SYK'),
  ('SYY', 'Sysco Corporation', 'stock', 'standard', 'common', 'fmp', 'SYY'),
  ('T', 'AT&T Inc.', 'stock', 'standard', 'common', 'fmp', 'T'),
  ('TAP', 'Molson Coors Beverage Company', 'stock', 'standard', 'common', 'fmp', 'TAP'),
  ('TDG', 'Transdigm Group Incorporated', 'stock', 'standard', 'common', 'fmp', 'TDG'),
  ('TDY', 'Teledyne Technologies Incorpora', 'stock', 'standard', 'common', 'fmp', 'TDY'),
  ('TECH', 'Bio-Techne Corp', 'stock', 'standard', 'common', 'fmp', 'TECH'),
  ('TEL', 'TE Connectivity plc', 'stock', 'standard', 'common', 'fmp', 'TEL'),
  ('TER', 'Teradyne, Inc.', 'stock', 'standard', 'common', 'fmp', 'TER'),
  ('TFC', 'Truist Financial Corporation', 'stock', 'standard', 'common', 'fmp', 'TFC'),
  ('TGT', 'Target Corporation', 'stock', 'standard', 'common', 'fmp', 'TGT'),
  ('TJX', 'TJX Companies, Inc. (The)', 'stock', 'standard', 'common', 'fmp', 'TJX'),
  ('TKO', 'TKO Group Holdings, Inc.', 'stock', 'standard', 'common', 'fmp', 'TKO'),
  ('TMO', 'Thermo Fisher Scientific Inc', 'stock', 'standard', 'common', 'fmp', 'TMO'),
  ('TMUS', 'T-Mobile US, Inc.', 'stock', 'standard', 'common', 'fmp', 'TMUS'),
  ('TPL', 'Texas Pacific Land Corporation', 'stock', 'standard', 'common', 'fmp', 'TPL'),
  ('TPR', 'Tapestry, Inc.', 'stock', 'standard', 'common', 'fmp', 'TPR'),
  ('TRGP', 'Targa Resources, Inc.', 'stock', 'standard', 'common', 'fmp', 'TRGP'),
  ('TRMB', 'Trimble Inc.', 'stock', 'standard', 'common', 'fmp', 'TRMB'),
  ('TROW', 'T. Rowe Price Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'TROW'),
  ('TRV', 'The Travelers Companies, Inc.', 'stock', 'standard', 'common', 'fmp', 'TRV'),
  ('TSCO', 'Tractor Supply Company', 'stock', 'standard', 'common', 'fmp', 'TSCO'),
  ('TSLA', 'Tesla, Inc.', 'stock', 'standard', 'common', 'fmp', 'TSLA'),
  ('TSN', 'Tyson Foods, Inc.', 'stock', 'standard', 'common', 'fmp', 'TSN'),
  ('TT', 'Trane Technologies plc', 'stock', 'standard', 'common', 'fmp', 'TT'),
  ('TTD', 'The Trade Desk, Inc.', 'stock', 'standard', 'common', 'fmp', 'TTD'),
  ('TTWO', 'Take-Two Interactive Software,', 'stock', 'standard', 'common', 'fmp', 'TTWO'),
  ('TXN', 'Texas Instruments Incorporated', 'stock', 'standard', 'common', 'fmp', 'TXN'),
  ('TXT', 'Textron Inc.', 'stock', 'standard', 'common', 'fmp', 'TXT'),
  ('TYL', 'Tyler Technologies, Inc.', 'stock', 'standard', 'common', 'fmp', 'TYL'),
  ('UAL', 'United Airlines Holdings, Inc.', 'stock', 'standard', 'common', 'fmp', 'UAL'),
  ('UBER', 'Uber Technologies, Inc.', 'stock', 'standard', 'common', 'fmp', 'UBER'),
  ('UDR', 'UDR, Inc.', 'stock', 'standard', 'common', 'fmp', 'UDR'),
  ('UHS', 'Universal Health Services, Inc.', 'stock', 'standard', 'common', 'fmp', 'UHS'),
  ('ULTA', 'Ulta Beauty, Inc.', 'stock', 'standard', 'common', 'fmp', 'ULTA'),
  ('UNH', 'UnitedHealth Group Incorporated', 'stock', 'standard', 'common', 'fmp', 'UNH'),
  ('UNP', 'Union Pacific Corporation', 'stock', 'standard', 'common', 'fmp', 'UNP'),
  ('UPS', 'United Parcel Service, Inc.', 'stock', 'standard', 'common', 'fmp', 'UPS'),
  ('URI', 'United Rentals, Inc.', 'stock', 'standard', 'common', 'fmp', 'URI'),
  ('USB', 'U.S. Bancorp', 'stock', 'standard', 'common', 'fmp', 'USB'),
  ('V', 'Visa Inc.', 'stock', 'standard', 'common', 'fmp', 'V'),
  ('VEEV', 'Veeva Systems Inc.', 'stock', 'standard', 'common', 'fmp', 'VEEV'),
  ('VICI', 'VICI Properties Inc.', 'stock', 'standard', 'common', 'fmp', 'VICI'),
  ('VLO', 'Valero Energy Corporation', 'stock', 'standard', 'common', 'fmp', 'VLO'),
  ('VLTO', 'Veralto Corp', 'stock', 'standard', 'common', 'fmp', 'VLTO'),
  ('VMC', 'Vulcan Materials Company (Holdi', 'stock', 'standard', 'common', 'fmp', 'VMC'),
  ('VRSK', 'Verisk Analytics, Inc.', 'stock', 'standard', 'common', 'fmp', 'VRSK'),
  ('VRSN', 'VeriSign, Inc.', 'stock', 'standard', 'common', 'fmp', 'VRSN'),
  ('VRT', 'Vertiv Holdings, LLC', 'stock', 'standard', 'common', 'fmp', 'VRT'),
  ('VRTX', 'Vertex Pharmaceuticals Incorpor', 'stock', 'standard', 'common', 'fmp', 'VRTX'),
  ('VST', 'Vistra Corp.', 'stock', 'standard', 'common', 'fmp', 'VST'),
  ('VTR', 'Ventas, Inc.', 'stock', 'standard', 'common', 'fmp', 'VTR'),
  ('VTRS', 'Viatris Inc.', 'stock', 'standard', 'common', 'fmp', 'VTRS'),
  ('VZ', 'Verizon Communications Inc.', 'stock', 'standard', 'common', 'fmp', 'VZ'),
  ('WAB', 'Westinghouse Air Brake Technolo', 'stock', 'standard', 'common', 'fmp', 'WAB'),
  ('WAT', 'Waters Corporation', 'stock', 'standard', 'common', 'fmp', 'WAT'),
  ('WBD', 'Warner Bros. Discovery, Inc. -', 'stock', 'standard', 'common', 'fmp', 'WBD'),
  ('WDAY', 'Workday, Inc.', 'stock', 'standard', 'common', 'fmp', 'WDAY'),
  ('WDC', 'Western Digital Corporation', 'stock', 'standard', 'common', 'fmp', 'WDC'),
  ('WEC', 'WEC Energy Group, Inc.', 'stock', 'standard', 'common', 'fmp', 'WEC'),
  ('WELL', 'Welltower Inc.', 'stock', 'standard', 'common', 'fmp', 'WELL'),
  ('WFC', 'Wells Fargo & Company', 'stock', 'standard', 'common', 'fmp', 'WFC'),
  ('WM', 'Waste Management, Inc.', 'stock', 'standard', 'common', 'fmp', 'WM'),
  ('WMB', 'Williams Companies, Inc. (The)', 'stock', 'standard', 'common', 'fmp', 'WMB'),
  ('WMT', 'Walmart Inc.', 'stock', 'standard', 'common', 'fmp', 'WMT'),
  ('WRB', 'W.R. Berkley Corporation', 'stock', 'standard', 'common', 'fmp', 'WRB'),
  ('WSM', 'Williams-Sonoma, Inc.', 'stock', 'standard', 'common', 'fmp', 'WSM'),
  ('WST', 'West Pharmaceutical Services, I', 'stock', 'standard', 'common', 'fmp', 'WST'),
  ('WTW', 'Willis Towers Watson Public Lim', 'stock', 'standard', 'common', 'fmp', 'WTW'),
  ('WY', 'Weyerhaeuser Company', 'stock', 'standard', 'common', 'fmp', 'WY'),
  ('WYNN', 'Wynn Resorts, Limited', 'stock', 'standard', 'common', 'fmp', 'WYNN'),
  ('XEL', 'Xcel Energy Inc.', 'stock', 'standard', 'common', 'fmp', 'XEL'),
  ('XOM', 'ExxonMobil Holdings Corporation', 'stock', 'standard', 'common', 'fmp', 'XOM'),
  ('XYL', 'Xylem Inc.', 'stock', 'standard', 'common', 'fmp', 'XYL'),
  ('XYZ', 'Block, Inc.', 'stock', 'standard', 'common', 'fmp', 'XYZ'),
  ('YUM', 'Yum! Brands, Inc.', 'stock', 'standard', 'common', 'fmp', 'YUM'),
  ('ZBH', 'Zimmer Biomet Holdings, Inc.', 'stock', 'standard', 'common', 'fmp', 'ZBH'),
  ('ZBRA', 'Zebra Technologies Corporation', 'stock', 'standard', 'common', 'fmp', 'ZBRA'),
  ('ZTS', 'Zoetis Inc.', 'stock', 'standard', 'common', 'fmp', 'ZTS')
on conflict (ticker) do nothing;

insert into public.securities
  (ticker, name, isin, asset_type, product_type, is_ucits, has_kid)
values
  ('ISWD', 'iShares MSCI World Islamic UCITS ETF', 'IE00B27YCN58', 'etf', 'standard', true, true)
on conflict (ticker) do nothing;
